

<!DOCTYPE html>
<html lang="en">

    <head>

        

    <script type="application/ld+json">

    {
    "@context": "http://schema.org",
    "@type": "BlogPosting",
    "headline": "Analyse The Airlines Passengers\x27 Satisfaction",
    "url": "https:\/\/lioneltayyd.github.io\/site\/machine_deep_learning\/customer_churn_analysis\/notebook\/analyse_the_airlines_passenger_satisfaction\/",
    "wordCount": "11477",
    "datePublished": "2020-05-01T22:36:38\x2b08:00",
    "dateModified": "2020-05-01T22:36:38\x2b08:00",
    "author": {
        "@type": "Person",
        "name": "Lionel Tay"
    }
    }

    </script> 



        <title>
    Analyse The Airlines Passengers&rsquo; Satisfaction
</title>


        
        <meta name="generator" content="Hugo 0.55.6" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta charset="UTF-8">
        <meta name="author" content=""/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        
        <meta name="description" content="Analyse The Airlines Passengers&amp;rsquo; Satisfaction Table of content.  1 Project Charter. 2 About the dataset. 3 Exploratory data analysis.  3.1 Investigate the data structure. 3.2 Explore categorical variables. 3.3 Explore numerical variables. 3.4 Check the correlation. 3.5 Investigate the ‘Age’ variable.   4 Investigate the cost of customer churn. 5 Data Preprocessing.  5.1 Prepare TRAIN and TEST set. 5.2 Double check if null exists.   6 Model training and evaluation."/>
        


        
        <link 
            rel="stylesheet" 
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
            crossorigin="anonymous">
        

        
        <script src="https://kit.fontawesome.com/c14bcac617.js"></script>

        

        
        
        <link href="https://lioneltayyd.github.io/site/css/custom.css" rel="stylesheet">
        <link href="https://lioneltayyd.github.io/site/css/syntax.css" rel="stylesheet">


        
        <link 
            href="https://fonts.googleapis.com/css?family=Martel:400,600,700|Montserrat:300,400,500,600,700|Muli:300,300i,400,400i,600,600i,700,700i,800,900|PT+Serif:400,400i,700,700i|Cutive+Mono|PT+Mono&display=swap&subset=latin-ext" 
            rel="stylesheet">
        


        
        <script 
    type="text/javascript"
    src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' 
    async>
</script>

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    displayMath: [['$$','$$'], ['\[','\]']],
    processEscapes: true,
    processEnvironments: true,
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre','code'],
    TeX: { equationNumbers: { autoNumber: "AMS" },
         extensions: ["AMSmath.js", "AMSsymbols.js"] }
  }
});
</script>

    </head>

    <body>

        
        <nav class="navbar navbar-expand-sm fixed-top">
            <div class="container">
                <a class="navbar-brand" href="https://lioneltayyd.github.io/site/">Lionel Tay</a>
                <button 
                    class="navbar-toggler" 
                    type="button" 
                    data-toggle="collapse" 
                    data-target="#navbarSupportedContent" 
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" 
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">   
                    <ul class="nav navbar-nav mr-auto"></ul>
                    <ul class="navbar-nav">

                        <li class="nav-item dropdown">
                            <a 
                                class="nav-link dropdown-toggle" 
                                href="#" 
                                id="navbarDropdown" 
                                role="button" 
                                data-toggle="dropdown" 
                                aria-haspopup="true"
                                aria-expanded="false">
                                About
                            </a>
                            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="https://lioneltayyd.github.io/site/about/about_me">About Me</a>
                                <a class="dropdown-item" href="https://github.com/lioneltayyd">GitHub</a>
                                <a class="dropdown-item" href="https://www.linkedin.com/in/lioneltayyd">LinkedIn</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a 
                                class="nav-link dropdown-toggle" 
                                href="#" 
                                id="navbarDropdown" 
                                role="button" 
                                data-toggle="dropdown" 
                                aria-haspopup="true"
                                aria-expanded="false">
                                Projects
                            </a>

                            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="https://lioneltayyd.github.io/site/data_statistical_analysis/anova_or_factorial_anova">Data & Statistical Analysis</a>
                                <a class="dropdown-item" href="https://lioneltayyd.github.io/site/dashboard_data_exploration/streamlit_dashboard">Dashboard & Data Exploration</a>
                                <a class="dropdown-item" href="https://lioneltayyd.github.io/site/machine_deep_learning/customer_churn_analysis">Machine & Deep Learning</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="https://lioneltayyd.github.io/site/blog">Blog</a>
                        </li>

                    </ul>
                </div>

            </div>
        </nav>


        
        
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
        
                     


<article>
  
  <div class="technical_note">
    <div class="content">    
      

<h1 id="analyse-the-airlines-passengers-satisfaction">Analyse The Airlines Passengers&rsquo; Satisfaction</h1>

<hr />

<h2 id="table-of-content">Table of content.</h2>

<div id="TOC">
    <ul>
        <li><a href="#1-project-charter">1 Project Charter.</a></li>
        <li><a href="#2-about-the-dataset">2 About the dataset.</a></li>
        <li><a href="#3-exploratory-data-analysis">3 Exploratory data analysis.</a>
            <ul>
                <li><a href="#3.1-investigate-the-data-structure">3.1 Investigate the data structure.</a></li>
                <li><a href="#3.2-explore-categorical-variables">3.2 Explore categorical variables.</a></li>
                <li><a href="#3.3-explore-numerical-variables">3.3 Explore numerical variables.</a></li>
                <li><a href="#3.4-check-the-correlation">3.4 Check the correlation.</a></li>
                <li><a href="#3.5-investigate-the-age-variable">3.5 Investigate the ‘Age’ variable.</a></li>
            </ul>
        </li>
        <li><a href="#4-investigate-the-cost-of-customer-churn">4 Investigate the cost of customer churn.</a></li>
        <li><a href="#5-data-preprocessing">5 Data Preprocessing.</a>
            <ul>
                <li><a href="#5.1-prepare-train-and-test-set">5.1 Prepare TRAIN and TEST set.</a></li>
                <li><a href="#5.2-double-check-if-null-exists">5.2 Double check if null exists.</a></li>
            </ul>
        </li>
        <li><a href="#6-model-training-and-evaluation">6 Model training and evaluation.</a>
            <ul>
            <li><a href="#6.1-train-logistic-model">6.1 Train Logistic model.</a></li>
            <li><a href="#6.2-train-decision-tree-model">6.2 Train Decision Tree model.</a></li>
            <li><a href="#6.3-train-random-forest-model">6.3 Train Random Forest model.</a></li>
            <li><a href="#6.4-train-xgboost-model">6.4 Train XGBoost model.</a></li>
            </ul>
        </li>
        <li><a href="#7-save-the-models">7 Save the models.</a></li>
        <li><a href="#8-model-comparison">8 Model comparison.</a></li>
        <li><a href="#9-model-interpretation">9 Model interpretation.</a></li>
        <li><a href="#10-explore-the-important-variables-effect-on-the-cost-of-customer-churn">10 Explore the important variable’s effect on the cost of customer churn.</a>
            <ul>
            <li><a href="#10.1-find-the-optimal-discriminant-threshold">10.1 Find the optimal discriminant threshold.</a></li>
            <li><a href="#10.2-compare-the-new-estimated-customer-churn-cost-after-improving-the-rating">10.2 Compare the new estimated customer churn cost after improving the rating.</a></li>
            <li><a href="#10.3-compare-the-proportion-of-the-neutralunsatisfied-customers-after-improving-the-rating">10.3 Compare the proportion of the neutral/unsatisfied customers after improving the rating.</a></li>
            </ul>
        </li>
        <li><a href="#11-conclusion">11 Conclusion.</a></li>
    </ul>
</div>

<hr />

<h2 id="1-project-charter">1 Project Charter.</h2>

<p><strong>Problem statement:</strong></p>

<p>Airline industry is getting more competitive due to the disruption of
budget airlines, which allow customers to travel to their destination at
a much cheaper price though with less service quality. If the customer
experience at Falcon Airlines is predominantly negative, it will quickly
become detrimental to the company’s profit due to high capital
expenditure and maintenance cost.</p>

<p><strong>Business case:</strong></p>

<p>Knowing the customers’ preference and feedback allows Falcon Airlines to
improve their standards and services on areas that matter to the
customers, and strategize the emotional selling points for their
marketing campaign to stand out among their competitors, hence
maintaining the company’s competitiveness and customer loyalty.</p>

<p><strong>Project goal:</strong></p>

<p>Predict whether a passenger will be satisfied or not given the rest of
the details are provided and identify which variables/features play an
important role in swaying a passenger feedback towards ‘satisfied’.</p>

<p><strong>Project scope:</strong></p>

<p>Perform data mining on the entire journey of the customers experience
beginning from website experience, online services, and departure to
onboard experience, flight duration, and arrival.</p>

<hr />

<h2 id="2-about-the-dataset">2 About the dataset.</h2>

<p><strong>There are 2 datasets:</strong></p>

<ol>
<li>The <code>Flight</code> data has information related to passengers and the
performance of flights in which they travelled.</li>
<li>The <code>Survey</code> data is the aggregated data of surveys collected post
service experience.</li>
</ol>

<p><strong>Assumptions about the survey:</strong></p>

<ol>
<li>Integrity: We assume customers are providing their honest and
careful feedback for the survey.</li>
<li>Situation &amp; context: We assume the customers aren’t hurry to
complete the survey after arriving at the destination and
experiencing the service since most customers (about 69%) are
business travellers as they could be busy with work. This would
result in a bias outcome.<br /></li>
<li>Question &amp; feedback: We assume those survey questions are what the
customers care about as the customers can’t fill in any feedback
other than choosing on a 1–5 scale based on those fixed questions.
The outcome will not be holistic if the company assumes these are
the only questions that matter to the customers. Additional research
has to be done to obtain a more accurate picture of our customers’
preference and feedback.</li>
</ol>

<p><strong>Data limitation:</strong></p>

<ol>
<li>The variables/features from the survey data will not be suitable to
train the model to predict the customers’ satisfaction, because we
will have to constantly gather the same survey data from new
customers to make future prediction which doesn’t make sense since
we could directly ask them to indicate their satisfaction level.
However, the goal of this project is to identify the important
variables/features that can significantly improve customers’
satisfaction. Hence, we are using the model to identify important
variables/features based on their effect on the satisfaction
outcome.</li>
<li>Survey is not perfect method for gathering customers’ preference and
feedback, hence additional research need to be done to obtain a more
holistic picture.</li>
</ol>

<hr />

<h2 id="3-exploratory-data-analysis">3 Exploratory data analysis.</h2>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">df_falconAirlines <span class="o">=</span> read_rds<span class="p">(</span><span class="s">&#39;00_dataset/df_falconAirlines.rds&#39;</span><span class="p">)</span>

<span class="kp">head</span><span class="p">(</span>df_falconAirlines<span class="p">,</span> <span class="m">10</span><span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 24
##    CustomerId Satisfaction Gate_location Seat_comfort Departure_Arriv…
##         &lt;dbl&gt; &lt;fct&gt;        &lt;fct&gt;         &lt;fct&gt;        &lt;fct&gt;           
##  1     149965 satisfied    need_improve… extremely_p… extremely_poor  
##  2     149966 satisfied    manageable    extremely_p… extremely_poor  
##  3     149967 satisfied    manageable    extremely_p… &lt;NA&gt;            
##  4     149968 satisfied    manageable    extremely_p… extremely_poor  
##  5     149969 satisfied    manageable    extremely_p… extremely_poor  
##  6     149970 satisfied    manageable    extremely_p… extremely_poor  
##  7     149971 satisfied    manageable    extremely_p… extremely_poor  
##  8     149972 satisfied    manageable    extremely_p… &lt;NA&gt;            
##  9     149973 satisfied    manageable    extremely_p… extremely_poor  
## 10     149974 satisfied    convenient    extremely_p… extremely_poor  
## # … with 19 more variables: Food_drink &lt;fct&gt;, Inflightwifi_service &lt;fct&gt;,
## #   Inflight_entertainment &lt;fct&gt;, Online_support &lt;fct&gt;,
## #   Ease_of_Onlinebooking &lt;fct&gt;, Onboard_service &lt;fct&gt;, Leg_room_service &lt;fct&gt;,
## #   Baggage_handling &lt;fct&gt;, Checkin_service &lt;fct&gt;, Cleanliness &lt;fct&gt;,
## #   Online_boarding &lt;fct&gt;, Gender &lt;fct&gt;, CustomerType &lt;fct&gt;, TypeTravel &lt;fct&gt;,
## #   Class &lt;fct&gt;, Age &lt;dbl&gt;, Flight_Distance &lt;dbl&gt;, DepartureDelayin_Mins &lt;dbl&gt;,
## #   ArrivalDelayin_Mins &lt;dbl&gt;
</code></pre>

<hr />

<h3 id="3-1-investigate-the-data-structure">3.1 Investigate the data structure.</h3>

<h4 id="3-1-1-check-duplicates">3.1.1 Check duplicates.</h4>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">df_falconAirlines <span class="o">%&gt;%</span> 
    <span class="kp">duplicated</span><span class="p">()</span> <span class="o">%&gt;%</span> 
    as_tibble<span class="p">()</span> <span class="o">%&gt;%</span> 
    summarise<span class="p">(</span>total_duplicates <span class="o">=</span> <span class="kp">sum</span><span class="p">(</span>value<span class="p">))</span> </code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   total_duplicates
##              &lt;int&gt;
## 1                0
</code></pre>

<hr />

<p><strong>Findings:</strong></p>

<ol>
<li>The joined dataset contains no duplicates.</li>
</ol>

<hr />

<h4 id="3-1-2-check-null-percentage">3.1.2 Check null percentage.</h4>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">df_falconAirlines <span class="o">%&gt;%</span> 
    summarise_all<span class="p">(</span><span class="o">~</span> <span class="kp">sum</span><span class="p">(</span><span class="kp">is.na</span><span class="p">(</span><span class="m">.</span><span class="p">))</span> <span class="o">/</span> <span class="kp">length</span><span class="p">(</span><span class="m">.</span><span class="p">)</span> <span class="o">*</span> <span class="m">100</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    gather<span class="p">()</span> <span class="o">%&gt;%</span> 
    filter<span class="p">(</span>value <span class="o">&gt;</span> <span class="m">0</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    set_names<span class="p">(</span><span class="kt">c</span><span class="p">(</span><span class="s">&#39;variables&#39;</span><span class="p">,</span> <span class="s">&#39;null_percent&#39;</span><span class="p">))</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>null_percent <span class="o">=</span> <span class="kp">round</span><span class="p">(</span>null_percent<span class="p">,</span> <span class="m">2</span><span class="p">))</span> </code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   variables                         null_percent
##   &lt;chr&gt;                                    &lt;dbl&gt;
## 1 Departure_Arrival_time_convenient         9.07
## 2 Food_drink                                9   
## 3 Onboard_service                           7.9 
## 4 CustomerType                             10.0 
## 5 TypeTravel                               10   
## 6 ArrivalDelayin_Mins                       0.31
</code></pre>

<hr />

<p><strong>Findings:</strong></p>

<ol>
<li><code>CustomersType</code> should contain either loyal or disloyal customers.
Null could probably mean the company is unable to accurately
identify the customers’ loyalty. I will apply Bagged Trees
Imputation to fill the null.</li>
<li><code>TypeTravel</code> should contain either business or personal travel. Null
could probably mean the company is unable to identify the customers’
travel motive. I will apply Bagged Trees Imputation to fill the
null.</li>
<li><code>ArrivalDelayin_Mins</code> contains 0.31% of null.</li>
<li><code>Departure_Arrival_time_convenient</code> contains 9% of null. It should
contain customer’s rating. Instead of assigning an “unknown”
category. I will apply Bagged Trees Imputation to fill the null so
that I can transform the variables into numerical ordinal values.</li>
<li>As for <code>Food_drink</code> and <code>Onboard_service</code>, null could probably mean
customers did not order any food and drink or ask for any onboard
service, thus no rating is given. Instead of assigning a “not
applicable” category, I will apply Bagged Trees Imputation to fill
the null instead so that I can transform the variables into
numerical ordinal values.</li>
</ol>

<hr />

<h4 id="3-1-3-summarise-data">3.1.3 Summarise data.</h4>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">df_falconAirlines <span class="o">%&gt;%</span> <span class="kp">summary</span><span class="p">()</span></code></pre></div>
<pre><code>##    CustomerId                      Satisfaction             Gate_location  
##  Min.   :149965   neutral_or dissatisfied:41156   very_inconvenient:    1  
##  1st Qu.:172694   satisfied              :49761   inconvenient     :15876  
##  Median :195423                                   need_improvement :17113  
##  Mean   :195423                                   manageable       :23385  
##  3rd Qu.:218152                                   convenient       :21088  
##  Max.   :240881                                   very_convenient  :13454  
##                                                                            
##            Seat_comfort   Departure_Arrival_time_convenient
##  extremely_poor  : 3368   extremely_poor  : 4199           
##  poor            :14687   poor            :13210           
##  need_improvement:20002   need_improvement:14539           
##  acceptable      :20552   acceptable      :14806           
##  good            :19789   good            :18840           
##  excellent       :12519   excellent       :17079           
##                           NA's            : 8244           
##             Food_drink          Inflightwifi_service
##  extremely_poor  : 3794   extremely_poor  :   96    
##  poor            :13400   poor            :10311    
##  need_improvement:17359   need_improvement:18894    
##  acceptable      :17991   acceptable      :19199    
##  good            :17245   good            :22159    
##  excellent       :12947   excellent       :20258    
##  NA's            : 8181                             
##       Inflight_entertainment          Online_support 
##  extremely_poor  : 2038      extremely_poor  :    1  
##  poor            : 8198      poor            : 9805  
##  need_improvement:13527      need_improvement:12063  
##  acceptable      :16995      acceptable      :15090  
##  good            :29373      good            :29042  
##  excellent       :20786      excellent       :24916  
##                                                      
##       Ease_of_Onlinebooking         Onboard_service          Leg_room_service
##  extremely_poor  :   12     extremely_poor  :    3   extremely_poor  :  322  
##  poor            : 9370     poor            : 8537   poor            : 7779  
##  need_improvement:13896     need_improvement:11018   need_improvement:15156  
##  acceptable      :15686     acceptable      :17411   acceptable      :15775  
##  good            :27993     good            :26373   good            :27814  
##  excellent       :23960     excellent       :20396   excellent       :24071  
##                             NA's            : 7179                           
##          Baggage_handling         Checkin_service            Cleanliness   
##  extremely_poor  :    0   extremely_poor  :    1   extremely_poor  :    4  
##  poor            : 5559   poor            :10761   poor            : 5375  
##  need_improvement: 9301   need_improvement:10813   need_improvement: 9283  
##  acceptable      :17233   acceptable      :24941   acceptable      :16930  
##  good            :33822   good            :25483   good            :34246  
##  excellent       :25002   excellent       :18918   excellent       :25079  
##                                                                            
##          Online_boarding     Gender                 CustomerType  
##  extremely_poor  :    9   female:46186   disloyal_customer:14921  
##  poor            :10777   male  :44731   loyal_customer   :66897  
##  need_improvement:13035                  NA's             : 9099  
##  acceptable      :21427                                           
##  good            :24676                                           
##  excellent       :20993                                           
##                                                                   
##            TypeTravel         Class            Age        Flight_Distance
##  business_travel:56481   eco     :40758   Min.   : 7.00   Min.   :  50   
##  personal_travel:25348   eco_plus: 6624   1st Qu.:27.00   1st Qu.:1360   
##  NA's           : 9088   business:43535   Median :40.00   Median :1927   
##                                           Mean   :39.45   Mean   :1982   
##                                           3rd Qu.:51.00   3rd Qu.:2542   
##                                           Max.   :85.00   Max.   :6950   
##                                                                          
##  DepartureDelayin_Mins ArrivalDelayin_Mins
##  Min.   :   0.00       Min.   :   0.00    
##  1st Qu.:   0.00       1st Qu.:   0.00    
##  Median :   0.00       Median :   0.00    
##  Mean   :  14.69       Mean   :  15.06    
##  3rd Qu.:  12.00       3rd Qu.:  13.00    
##  Max.   :1592.00       Max.   :1584.00    
##                        NA's   :284
</code></pre>

<hr />

<h3 id="3-2-explore-categorical-variables">3.2 Explore categorical variables.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Check target variable&#39;s class proprotion. </span>
df_falconAirlines<span class="o">$</span>Satisfaction <span class="o">%&gt;%</span> <span class="kp">summary</span><span class="p">()</span> <span class="o">/</span> <span class="kp">nrow</span><span class="p">(</span>df_falconAirlines<span class="p">)</span></code></pre></div>
<pre><code>## neutral_or dissatisfied               satisfied 
##               0.4526766               0.5473234
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Visualise the distribution. </span>
plotBarCat<span class="p">(</span>df_falconAirlines<span class="p">,</span> <span class="s">&#39;Satisfaction&#39;</span><span class="p">)</span></code></pre></div>
<p><img src="unnamed-chunk-5-1.png" style="display: block; margin: auto auto auto 0;" /></p>

<hr />

<p><strong>Findings from the target variable:</strong></p>

<ol>
<li>Looking at the <code>Satisfaction</code> variable, about 46% of the customers
feel neutral/dissatisfied, whereas 54% feel satisfied. Hence, the
dataset has a balanced class.</li>
</ol>

<hr />
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">flightCat <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;CustomerType&#39;</span><span class="p">,</span> <span class="s">&#39;TypeTravel&#39;</span><span class="p">,</span> <span class="s">&#39;Class&#39;</span><span class="p">)</span>

<span class="kr">for</span> <span class="p">(</span>cat <span class="kr">in</span> flightCat<span class="p">)</span> <span class="p">{</span>
    df_falconAirlines <span class="o">%&gt;%</span>
        plotInteract<span class="p">(</span><span class="s">&#39;Satisfaction&#39;</span><span class="p">,</span> <span class="kp">cat</span><span class="p">,</span> <span class="s">&#39;Satisfaction&#39;</span><span class="p">)</span>
<span class="p">}</span></code></pre></div>
<p><img src="unnamed-chunk-6-1.png" style="display: block; margin: auto auto auto 0;" />
<img src="unnamed-chunk-6-2.png" style="display: block; margin: auto auto auto 0;" />
<img src="unnamed-chunk-6-3.png" style="display: block; margin: auto auto auto 0;" /></p>

<hr />

<p><strong>Findings from the variable’s interaction with customer satisfaction:</strong></p>

<ol>
<li>Each of the variables/features above seem to contribute a medium
impact to the model predictability looking how the lines show the
opposite trend or direction.</li>
</ol>

<hr />

<h3 id="3-3-explore-numerical-variables">3.3 Explore numerical variables.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">numPlot1 <span class="o">=</span> plotDensityNum<span class="p">(</span>df_falconAirlines<span class="p">,</span> <span class="s">&#39;Age&#39;</span><span class="p">,</span> <span class="s">&#39;Satisfaction&#39;</span><span class="p">)</span>
numPlot2 <span class="o">=</span> plotDensityNum<span class="p">(</span>df_falconAirlines<span class="p">,</span> <span class="s">&#39;Flight_Distance&#39;</span><span class="p">,</span> <span class="s">&#39;Satisfaction&#39;</span><span class="p">)</span>

multi_plot <span class="o">=</span> grid.arrange<span class="p">(</span>numPlot1<span class="p">,</span> numPlot2<span class="p">,</span> nrow<span class="o">=</span><span class="m">2</span><span class="p">,</span> ncol<span class="o">=</span><span class="m">1</span><span class="p">)</span></code></pre></div>
<p><img src="unnamed-chunk-7-1.png" style="display: block; margin: auto auto auto 0;" /></p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Zoomed in the plot. </span>
numPlot3 <span class="o">=</span> plotDensityNumLim<span class="p">(</span>df_falconAirlines<span class="p">,</span> <span class="s">&#39;DepartureDelayin_Mins&#39;</span><span class="p">,</span> <span class="s">&#39;Satisfaction&#39;</span><span class="p">)</span>
numPlot4 <span class="o">=</span> plotDensityNumLim<span class="p">(</span>df_falconAirlines<span class="p">,</span> <span class="s">&#39;ArrivalDelayin_Mins&#39;</span><span class="p">,</span> <span class="s">&#39;Satisfaction&#39;</span><span class="p">)</span>

multi_plot <span class="o">=</span> grid.arrange<span class="p">(</span>numPlot3<span class="p">,</span> numPlot4<span class="p">,</span> nrow<span class="o">=</span><span class="m">2</span><span class="p">,</span> ncol<span class="o">=</span><span class="m">1</span><span class="p">)</span></code></pre></div>
<p><img src="unnamed-chunk-8-1.png" style="display: block; margin: auto auto auto 0;" /></p>

<hr />

<p><strong>Findings:</strong></p>

<ol>
<li>Looking at the <code>Age</code> feature, there is a small separation between
the 2 distributions. It seems that there are greater proportion of
customers below age 40 feel neutral/dissatisfied than those above
age 40. I will discretise the numerical value into categorical bins
to improve the feature interpretability when investigating the
feature weight or importance.</li>
<li>Looking at the <code>Flight_Distance</code> feature, there is no significant
separation between the 2 distributions. It might be a weak predictor
for customers’ satisfaction, hence I will remove it.</li>
<li>Looking at <code>DepartureDelayin_Mins</code> and <code>ArrivalDelayin_Mins</code>
features, both shows only a slight separation between the 2
distributions (red and turquoise). I will keep these variables to
see how it performs.</li>
</ol>

<hr />

<h3 id="3-4-check-the-correlation">3.4 Check the correlation.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Find correlation between each numerical variables. </span>
df_falconAirlines <span class="o">%&gt;%</span> 
    select<span class="p">(</span>Age<span class="p">,</span> Flight_Distance<span class="p">,</span> DepartureDelayin_Mins<span class="p">,</span> ArrivalDelayin_Mins<span class="p">)</span> <span class="o">%&gt;%</span> 
    cor<span class="p">(</span>method<span class="o">=</span><span class="s">&#34;pearson&#34;</span><span class="p">,</span> use<span class="o">=</span><span class="s">&#34;pairwise.complete.obs&#34;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    <span class="kp">round</span><span class="p">(</span><span class="m">2</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    get_lower_tri<span class="p">()</span> </code></pre></div>
<pre><code>##                         Age Flight_Distance DepartureDelayin_Mins
## Age                    1.00              NA                    NA
## Flight_Distance       -0.25            1.00                    NA
## DepartureDelayin_Mins -0.01            0.11                  1.00
## ArrivalDelayin_Mins   -0.01            0.11                  0.97
##                       ArrivalDelayin_Mins
## Age                                    NA
## Flight_Distance                        NA
## DepartureDelayin_Mins                  NA
## ArrivalDelayin_Mins                     1
</code></pre>

<hr />

<p><strong>Findings from the correlation between numerical variables:</strong></p>

<ol>
<li><code>DepartureDelayin_Mins</code> and <code>ArrivalDelayin_Mins</code> have a correlation
of 0.97. I will remove <code>ArrivalDelayin_Mins</code> since it contains 0.31%
of null.</li>
</ol>

<hr />
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Find correlation between each numerical and categorical variables. </span>
corr_results <span class="o">=</span> df_falconAirlines <span class="o">%&gt;%</span> 
    select<span class="p">(</span><span class="o">-</span>CustomerId<span class="p">,</span> <span class="o">-</span>CustomerType<span class="p">,</span> <span class="o">-</span>TypeTravel<span class="p">,</span> <span class="o">-</span>Gender<span class="p">,</span> <span class="o">-</span>Satisfaction<span class="p">)</span> <span class="o">%&gt;%</span> 
    mutate_all<span class="p">(</span><span class="kp">as.numeric</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    cor<span class="p">(</span>method<span class="o">=</span><span class="s">&#34;spearman&#34;</span><span class="p">,</span> use<span class="o">=</span><span class="s">&#34;pairwise.complete.obs&#34;</span><span class="p">)</span> 

<span class="c1"># For selecting variables that have correlation above 0.6</span>
cols <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;Online_support&#39;</span><span class="p">,</span> <span class="s">&#39;Ease_of_Onlinebooking&#39;</span><span class="p">,</span>
         <span class="s">&#39;Seat_comfort&#39;</span><span class="p">,</span> <span class="s">&#39;Food_drink&#39;</span><span class="p">,</span> <span class="s">&#39;Online_boarding&#39;</span><span class="p">)</span>

<span class="c1"># Display the correlation results. </span>
corr_results<span class="p">[</span>cols<span class="p">,</span> cols<span class="p">]</span> <span class="o">%&gt;%</span> 
    <span class="kp">round</span><span class="p">(</span><span class="m">2</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    get_lower_tri<span class="p">()</span> </code></pre></div>
<pre><code>##                       Online_support Ease_of_Onlinebooking Seat_comfort
## Online_support                  1.00                    NA           NA
## Ease_of_Onlinebooking           0.60                  1.00           NA
## Seat_comfort                    0.12                  0.20         1.00
## Food_drink                      0.03                  0.03         0.71
## Online_boarding                 0.65                  0.66         0.13
##                       Food_drink Online_boarding
## Online_support                NA              NA
## Ease_of_Onlinebooking         NA              NA
## Seat_comfort                  NA              NA
## Food_drink                  1.00              NA
## Online_boarding             0.01               1
</code></pre>

<hr />

<p><strong>Findings from the Spearman correlation between ordinal variables:</strong></p>

<ol>
<li><code>Ease_of_Onlinebooking</code>, <code>Online_boarding</code>, <code>Online_support</code> are
about 60% correlated. It probably makes sense because these
variables contribute to the overall user experience, hence should be
taken in consideration as a whole should Falcon Airlines makes any
improvement to the website or app.</li>
<li><code>Food_drink</code> and <code>seat_comfort</code> are about 70% correlated.</li>
</ol>

<p>I can apply variance inflation factor when training the logistic
regression model to avoid multi-collinearity issue.</p>

<hr />
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Select categorical variable names. </span>
catNames <span class="o">=</span> df_falconAirlines <span class="o">%&gt;%</span> 
    select_if<span class="p">(</span><span class="kp">is.factor</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    <span class="kp">names</span><span class="p">()</span>

<span class="c1"># Preview.</span>
catNames</code></pre></div>
<pre><code>##  [1] &quot;Satisfaction&quot;                      &quot;Gate_location&quot;                    
##  [3] &quot;Seat_comfort&quot;                      &quot;Departure_Arrival_time_convenient&quot;
##  [5] &quot;Food_drink&quot;                        &quot;Inflightwifi_service&quot;             
##  [7] &quot;Inflight_entertainment&quot;            &quot;Online_support&quot;                   
##  [9] &quot;Ease_of_Onlinebooking&quot;             &quot;Onboard_service&quot;                  
## [11] &quot;Leg_room_service&quot;                  &quot;Baggage_handling&quot;                 
## [13] &quot;Checkin_service&quot;                   &quot;Cleanliness&quot;                      
## [15] &quot;Online_boarding&quot;                   &quot;Gender&quot;                           
## [17] &quot;CustomerType&quot;                      &quot;TypeTravel&quot;                       
## [19] &quot;Class&quot;
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Find correlation between each categorical variables with `Satisfaction`. </span>
df_falconAirlines <span class="o">%&gt;%</span> 
    cramer_corr<span class="p">(</span>catNames<span class="p">,</span> <span class="s">&#39;Satisfaction&#39;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.data.frame</span><span class="p">()</span> <span class="o">%&gt;%</span> 
    filter<span class="p">(</span>variable <span class="o">!=</span> <span class="s">&#39;Baggage_handling&#39;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    arrange<span class="p">(</span>desc<span class="p">(</span>cramer<span class="p">))</span> </code></pre></div>
<pre><code>##                             variable             cramer
## 1             Inflight_entertainment  0.639268085016792
## 2                       Seat_comfort  0.471769575989941
## 3              Ease_of_Onlinebooking  0.453261862571313
## 4                     Online_support  0.431646347233728
## 5                    Onboard_service  0.360286620354981
## 6                    Online_boarding  0.348133711652928
## 7                   Leg_room_service  0.337433279445608
## 8                              Class  0.314836878500457
## 9                        Cleanliness  0.304914968262666
## 10                      CustomerType  0.293597832545281
## 11                   Checkin_service  0.281377235539842
## 12                        Food_drink  0.265839591386635
## 13              Inflightwifi_service  0.243609829903224
## 14                            Gender  0.211114521751906
## 15                     Gate_location   0.14568970482666
## 16                        TypeTravel  0.111038588549111
## 17 Departure_Arrival_time_convenient 0.0459484483394978
</code></pre>

<hr />

<p><strong>Findings from Cramer results for ordinal and categorical variables:</strong></p>

<ol>
<li><code>Inflight_entertainment</code> seems to have very strong relationship
(0.63) with <code>Satisfaction</code> (target variable), followed by
<code>Seat_comfort</code>, <code>Ease_of_Onlinebooking</code>, <code>Online_support</code> and
<code>Onboard_service</code>. These variables might be relatively strong
predictors for customers’ satisfaction.</li>
</ol>

<hr />

<h3 id="3-5-investigate-the-age-variable">3.5 Investigate the ‘Age’ variable.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Output the cumulative percentage of customers with different age. </span>
df_falconAirlines <span class="o">%&gt;%</span> 
    group_by<span class="p">(</span>Age<span class="p">)</span> <span class="o">%&gt;%</span> 
    summarise<span class="p">(</span>Percent <span class="o">=</span> n<span class="p">()</span> <span class="o">/</span> <span class="kp">nrow</span><span class="p">(</span>df_falconAirlines<span class="p">))</span> <span class="o">%&gt;%</span> 
    ungroup<span class="p">()</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>Cumsum <span class="o">=</span> scales<span class="o">::</span>percent<span class="p">(</span><span class="kp">cumsum</span><span class="p">(</span>Percent<span class="p">)),</span> 
           Percent <span class="o">=</span> scales<span class="o">::</span>percent<span class="p">(</span>Percent<span class="p">))</span> <span class="o">%&gt;%</span> 
    filter<span class="p">(</span>Age <span class="o">&lt;=</span> <span class="m">21</span><span class="p">)</span> </code></pre></div>
<pre><code>## # A tibble: 15 x 3
##      Age Percent Cumsum
##    &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt; 
##  1     7 0.51%   0.5%  
##  2     8 0.60%   1.1%  
##  3     9 0.68%   1.8%  
##  4    10 0.62%   2.4%  
##  5    11 0.64%   3.0%  
##  6    12 0.61%   3.7%  
##  7    13 0.62%   4.3%  
##  8    14 0.66%   4.9%  
##  9    15 0.78%   5.7%  
## 10    16 0.90%   6.6%  
## 11    17 0.94%   7.6%  
## 12    18 0.93%   8.5%  
## 13    19 0.89%   9.4%  
## 14    20 1.49%   10.9% 
## 15    21 1.46%   12.3%
</code></pre>

<hr />

<p><strong>Findings:</strong></p>

<ol>
<li>Looking at the table below, there are about 8.5% of the customers
who are age 18 or below. We want to focus on customers who have the
purchasing/decision power to make a purchase. Hence, I will remove
respondents who are aged 18 or below as their preferences and
opinions provide little value to the business, assuming that these
respondents do not or have little purchasing/decision power.</li>
</ol>

<hr />

<h2 id="4-investigate-the-cost-of-customer-churn">4 Investigate the cost of customer churn.</h2>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">df_falconAirlines <span class="o">%&gt;%</span> 
    compute_customer_life_time_value<span class="p">(</span>travel_type_colname<span class="o">=</span>TypeTravel<span class="p">)</span> <span class="o">%&gt;%</span> 
    life_time_value_by_customer_type<span class="p">(</span>Satisfaction<span class="p">,</span> CustomerType<span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   Satisfaction            CustomerType      total_customer_life_time_value
##   &lt;fct&gt;                   &lt;fct&gt;             &lt;chr&gt;                         
## 1 neutral_or dissatisfied disloyal_customer $23,957,000                   
## 2 neutral_or dissatisfied loyal_customer    $38,268,350                   
## 3 neutral_or dissatisfied &lt;NA&gt;              $7,683,650                    
## 4 satisfied               disloyal_customer $9,029,150                    
## 5 satisfied               loyal_customer    $93,829,650                   
## 6 satisfied               &lt;NA&gt;              $11,864,000
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">df_falconAirlines <span class="o">%&gt;%</span> 
    compute_customer_life_time_value<span class="p">(</span>travel_type_colname<span class="o">=</span>TypeTravel<span class="p">)</span> <span class="o">%&gt;%</span> 
    life_time_value_by_customer_type<span class="p">(</span>Satisfaction<span class="p">,</span> CustomerType<span class="p">,</span> TypeTravel<span class="p">)</span> </code></pre></div>
<pre><code>## # A tibble: 16 x 4
##    Satisfaction         CustomerType     TypeTravel    total_customer_life_time…
##    &lt;fct&gt;                &lt;fct&gt;            &lt;fct&gt;         &lt;chr&gt;                    
##  1 neutral_or dissatis… disloyal_custom… business_tra… $22,931,550              
##  2 neutral_or dissatis… disloyal_custom… personal_tra… $52,950                  
##  3 neutral_or dissatis… disloyal_custom… &lt;NA&gt;          $972,500                 
##  4 neutral_or dissatis… loyal_customer   business_tra… $29,359,650              
##  5 neutral_or dissatis… loyal_customer   personal_tra… $6,861,000               
##  6 neutral_or dissatis… loyal_customer   &lt;NA&gt;          $2,047,700               
##  7 neutral_or dissatis… &lt;NA&gt;             business_tra… $6,808,650               
##  8 neutral_or dissatis… &lt;NA&gt;             personal_tra… $875,000                 
##  9 satisfied            disloyal_custom… business_tra… $8,676,900               
## 10 satisfied            disloyal_custom… personal_tra… $9,750                   
## 11 satisfied            disloyal_custom… &lt;NA&gt;          $342,500                 
## 12 satisfied            loyal_customer   business_tra… $83,569,350              
## 13 satisfied            loyal_customer   personal_tra… $5,996,450               
## 14 satisfied            loyal_customer   &lt;NA&gt;          $4,263,850               
## 15 satisfied            &lt;NA&gt;             business_tra… $11,116,350              
## 16 satisfied            &lt;NA&gt;             personal_tra… $747,650
</code></pre>

<hr />

<p><strong>Findings:</strong></p>

<ol>
<li>The life time value cost of losing the entire loyal customers who
are neutral/dissatisfied is about 38.3 million. As for the “NA”
customer type who are neutral or dissatisfied, assuming there are
50% of loyal customers, the life time value cost would be about 3.8
million. Total would be about 42.1 million.</li>
<li>Given the entire loyal customers who are neutral/dissatisfied, the
life time value cost of losing the Business Travelers is about 29.4
million compare to Personal Travellers, which is 6.9 million. While
the “NA” (unknown travel type) costs about 2 million. Given the
entire “NA” customer type, assuming there are 50% of loyal
customers, the total life time value cost of losing the Business and
Personal Travelers would be about 3.85 million.</li>
</ol>

<p>I will not be focusing on the life time value cost for the disloyal
customers since they do not stick with FalconAirlines unless our project
goal includes turning the disloyal customers into loyal via customer
satisfaction.</p>

<p>I will later explore with the important variables to estimate the change
in proportion of customer feeling satisfied and potential reduction in
customer churn cost after building the model.</p>

<hr />

<h2 id="5-data-preprocessing">5 Data Preprocessing.</h2>

<h3 id="5-1-prepare-train-and-test-set">5.1 Prepare TRAIN and TEST set.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="kp">set.seed</span><span class="p">(</span>seed<span class="o">=</span><span class="m">5</span><span class="p">)</span>
split_obj <span class="o">=</span> rsample<span class="o">::</span>initial_split<span class="p">(</span>df_falconAirlines<span class="p">,</span> prop<span class="o">=</span><span class="m">0.70</span><span class="p">)</span>

<span class="c1"># Split the data.</span>
df_train <span class="o">=</span> training<span class="p">(</span>split_obj<span class="p">)</span>
df_test <span class="o">=</span> testing<span class="p">(</span>split_obj<span class="p">)</span></code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Check the value proportion of the target variable. </span>
<span class="kt">list</span><span class="p">(</span>
    TRAIN <span class="o">=</span> df_train<span class="o">$</span>Satisfaction <span class="o">%&gt;%</span> <span class="kp">summary</span><span class="p">()</span> <span class="o">/</span> <span class="kp">nrow</span><span class="p">(</span>df_train<span class="p">),</span> 
    TEST <span class="o">=</span> df_test<span class="o">$</span>Satisfaction <span class="o">%&gt;%</span> <span class="kp">summary</span><span class="p">()</span> <span class="o">/</span> <span class="kp">nrow</span><span class="p">(</span>df_test<span class="p">)</span>
<span class="p">)</span> </code></pre></div>
<pre><code>## $TRAIN
## neutral_or dissatisfied               satisfied 
##                0.454904                0.545096 
## 
## $TEST
## neutral_or dissatisfied               satisfied 
##               0.4474794               0.5525206
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># ---------------------------------------------</span>
<span class="c1"># Prepare the variables. </span>
<span class="c1"># ---------------------------------------------</span>

<span class="c1"># To indicate which variables will be used for Bagging Imputation. </span>
impute_with_vars <span class="o">=</span> df_falconAirlines <span class="o">%&gt;%</span> 
    select<span class="p">(</span><span class="o">-</span>CustomerId<span class="p">,</span> <span class="o">-</span>Satisfaction<span class="p">,</span> <span class="o">-</span>Gender<span class="p">,</span> <span class="o">-</span>ArrivalDelayin_Mins<span class="p">,</span> <span class="o">-</span>Flight_Distance<span class="p">)</span> <span class="o">%&gt;%</span> 
    <span class="kp">colnames</span><span class="p">()</span>

<span class="c1"># To indicate which variables should be processed. </span>
remove_vars <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;ArrivalDelayin_Mins&#39;</span><span class="p">,</span> <span class="s">&#39;Flight_Distance&#39;</span><span class="p">,</span> <span class="s">&#39;Gender&#39;</span><span class="p">)</span>
missing_vars <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;CustomerType&#39;</span><span class="p">,</span> <span class="s">&#39;TypeTravel&#39;</span><span class="p">,</span> <span class="s">&#39;Departure_Arrival_time_convenient&#39;</span><span class="p">,</span> 
                 <span class="s">&#39;Onboard_service&#39;</span><span class="p">,</span> <span class="s">&#39;Food_drink&#39;</span><span class="p">)</span>
binning_vars <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;Age&#39;</span><span class="p">)</span>
dummy_vars <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;CustomerType&#39;</span><span class="p">,</span> <span class="s">&#39;TypeTravel&#39;</span><span class="p">,</span> <span class="s">&#39;Age&#39;</span><span class="p">)</span>
dist_transform_vars <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;DepartureDelayin_Mins&#39;</span><span class="p">)</span> 
normalise_vars <span class="o">=</span> <span class="kt">c</span><span class="p">(</span><span class="s">&#39;DepartureDelayin_Mins&#39;</span><span class="p">)</span> 

<span class="c1"># ---------------------------------------------</span>
<span class="c1"># Construct processing pipeline.</span>
<span class="c1"># ---------------------------------------------</span>

recipe_obj <span class="o">=</span> recipe<span class="p">(</span>Satisfaction <span class="o">~</span> <span class="m">.</span><span class="p">,</span> data<span class="o">=</span>df_train<span class="p">)</span> <span class="o">%&gt;%</span> 
    step_rm<span class="p">(</span>remove_vars<span class="p">)</span> <span class="o">%&gt;%</span> 
    step_filter<span class="p">(</span>Age <span class="o">&gt;</span> <span class="m">18</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    step_bagimpute<span class="p">(</span>missing_vars<span class="p">,</span> impute_with<span class="o">=</span>impute_with_vars<span class="p">,</span> seed_val<span class="o">=</span><span class="m">5</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    step_mutate_at<span class="p">(</span>binning_vars<span class="p">,</span> fn<span class="o">=</span>binning<span class="p">)</span> <span class="o">%&gt;%</span> 
    step_dummy<span class="p">(</span>dummy_vars<span class="p">)</span> <span class="o">%&gt;%</span> 
    step_rename_at<span class="p">(</span>all_predictors<span class="p">(),</span> fn<span class="o">=</span> <span class="o">~</span> str_replace_all<span class="p">(</span><span class="m">.</span><span class="p">,</span> <span class="s">&#39;\\.&#39;</span><span class="p">,</span> <span class="s">&#39;_&#39;</span><span class="p">))</span> <span class="o">%&gt;%</span> 
    step_mutate_at<span class="p">(</span>all_predictors<span class="p">(),</span> fn<span class="o">=</span><span class="kp">as.numeric</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    step_YeoJohnson<span class="p">(</span>dist_transform_vars<span class="p">)</span> <span class="o">%&gt;%</span> 
    step_normalize<span class="p">(</span>normalise_vars<span class="p">)</span> <span class="o">%&gt;%</span> 
    prep<span class="p">()</span> 

<span class="c1"># ---------------------------------------------</span>
<span class="c1"># Execute the pipeline. </span>
<span class="c1"># ---------------------------------------------</span>
 
<span class="c1"># Keep the customer ID so I can identify the row later. </span>

df_train_processed_with_id <span class="o">=</span> recipe_obj <span class="o">%&gt;%</span>
    juice<span class="p">()</span> 

df_test_processed_with_id <span class="o">=</span> recipe_obj <span class="o">%&gt;%</span> 
    bake<span class="p">(</span>new_data<span class="o">=</span>df_test<span class="p">)</span> </code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Remove customer ID when it is used for model training. </span>

df_train_processed <span class="o">=</span> df_train_processed_with_id <span class="o">%&gt;%</span> 
    select<span class="p">(</span><span class="o">-</span>CustomerId<span class="p">)</span>

df_test_processed <span class="o">=</span> df_test_processed_with_id <span class="o">%&gt;%</span> 
    select<span class="p">(</span><span class="o">-</span>CustomerId<span class="p">)</span></code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Check the processed data. </span>
df_train_processed <span class="o">%&gt;%</span> 
    <span class="kp">summary</span><span class="p">()</span></code></pre></div>
<pre><code>##  Gate_location    Seat_comfort   Departure_Arrival_time_convenient
##  Min.   :2.000   Min.   :1.000   Min.   :1.000                    
##  1st Qu.:3.000   1st Qu.:3.000   1st Qu.:3.000                    
##  Median :4.000   Median :4.000   Median :4.000                    
##  Mean   :3.988   Mean   :3.838   Mean   :3.968                    
##  3rd Qu.:5.000   3rd Qu.:5.000   3rd Qu.:5.000                    
##  Max.   :6.000   Max.   :6.000   Max.   :6.000                    
##    Food_drink    Inflightwifi_service Inflight_entertainment Online_support 
##  Min.   :1.000   Min.   :1.000        Min.   :1.000          Min.   :1.000  
##  1st Qu.:3.000   1st Qu.:3.000        1st Qu.:3.000          1st Qu.:4.000  
##  Median :4.000   Median :4.000        Median :5.000          Median :5.000  
##  Mean   :3.856   Mean   :4.256        Mean   :4.409          Mean   :4.539  
##  3rd Qu.:5.000   3rd Qu.:5.000        3rd Qu.:5.000          3rd Qu.:6.000  
##  Max.   :6.000   Max.   :6.000        Max.   :6.000          Max.   :6.000  
##  Ease_of_Onlinebooking Onboard_service Leg_room_service Baggage_handling
##  Min.   :1.000         Min.   :1.000   Min.   :1.000    Min.   :2.000   
##  1st Qu.:3.000         1st Qu.:4.000   1st Qu.:3.000    1st Qu.:4.000   
##  Median :5.000         Median :5.000   Median :5.000    Median :5.000   
##  Mean   :4.489         Mean   :4.475   Mean   :4.496    Mean   :4.693   
##  3rd Qu.:6.000         3rd Qu.:5.000   3rd Qu.:6.000    3rd Qu.:6.000   
##  Max.   :6.000         Max.   :6.000   Max.   :6.000    Max.   :6.000   
##  Checkin_service  Cleanliness    Online_boarding     Class      
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:4.000   1st Qu.:4.000   1st Qu.:3.000   1st Qu.:1.000  
##  Median :4.000   Median :5.000   Median :5.000   Median :3.000  
##  Mean   :4.341   Mean   :4.704   Mean   :4.366   Mean   :2.083  
##  3rd Qu.:5.000   3rd Qu.:6.000   3rd Qu.:5.000   3rd Qu.:3.000  
##  Max.   :6.000   Max.   :6.000   Max.   :6.000   Max.   :3.000  
##  DepartureDelayin_Mins                  Satisfaction  
##  Min.   :-0.8303       neutral_or dissatisfied:25854  
##  1st Qu.:-0.8303       satisfied              :32438  
##  Median :-0.8303                                      
##  Mean   : 0.0000                                      
##  3rd Qu.: 1.1222                                      
##  Max.   : 1.8065                                      
##  CustomerType_loyal_customer TypeTravel_personal_travel  Age_X_20_25_   
##  Min.   :0.000               Min.   :0.000              Min.   :0.0000  
##  1st Qu.:1.000               1st Qu.:0.000              1st Qu.:0.0000  
##  Median :1.000               Median :0.000              Median :0.0000  
##  Mean   :0.815               Mean   :0.271              Mean   :0.1054  
##  3rd Qu.:1.000               3rd Qu.:1.000              3rd Qu.:0.0000  
##  Max.   :1.000               Max.   :1.000              Max.   :1.0000  
##   Age_X_25_30_     Age_X_30_35_      Age_X_35_40_     Age_X_40_45_   
##  Min.   :0.0000   Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.0000   Median :0.00000   Median :0.0000   Median :0.0000  
##  Mean   :0.1153   Mean   :0.09255   Mean   :0.1248   Mean   :0.1309  
##  3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.0000  
##  Max.   :1.0000   Max.   :1.00000   Max.   :1.0000   Max.   :1.0000  
##   Age_X_45_50_     Age_X_50_55_     Age_X_55_60_      Age_X_60_65_    
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000  
##  Median :0.0000   Median :0.0000   Median :0.00000   Median :0.00000  
##  Mean   :0.1183   Mean   :0.1058   Mean   :0.09494   Mean   :0.05239  
##  3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.00000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.00000   Max.   :1.00000  
##  Age_X_65_above_  
##  Min.   :0.00000  
##  1st Qu.:0.00000  
##  Median :0.00000  
##  Mean   :0.05004  
##  3rd Qu.:0.00000  
##  Max.   :1.00000
</code></pre>

<hr />

<h3 id="5-2-double-check-if-null-exists">5.2 Double check if null exists.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Check null proportion for each variable.</span>
df_train_processed <span class="o">%&gt;%</span> 
    summarise_all<span class="p">(</span><span class="o">~</span> <span class="kp">sum</span><span class="p">(</span><span class="kp">is.na</span><span class="p">(</span><span class="m">.</span><span class="p">))</span> <span class="o">/</span> <span class="kp">length</span><span class="p">(</span><span class="m">.</span><span class="p">)</span> <span class="o">*</span> <span class="m">100</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    gather<span class="p">()</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       key                                 value
##  [1,] &quot;Gate_location&quot;                     &quot;0&quot;  
##  [2,] &quot;Seat_comfort&quot;                      &quot;0&quot;  
##  [3,] &quot;Departure_Arrival_time_convenient&quot; &quot;0&quot;  
##  [4,] &quot;Food_drink&quot;                        &quot;0&quot;  
##  [5,] &quot;Inflightwifi_service&quot;              &quot;0&quot;  
##  [6,] &quot;Inflight_entertainment&quot;            &quot;0&quot;  
##  [7,] &quot;Online_support&quot;                    &quot;0&quot;  
##  [8,] &quot;Ease_of_Onlinebooking&quot;             &quot;0&quot;  
##  [9,] &quot;Onboard_service&quot;                   &quot;0&quot;  
## [10,] &quot;Leg_room_service&quot;                  &quot;0&quot;  
## [11,] &quot;Baggage_handling&quot;                  &quot;0&quot;  
## [12,] &quot;Checkin_service&quot;                   &quot;0&quot;  
## [13,] &quot;Cleanliness&quot;                       &quot;0&quot;  
## [14,] &quot;Online_boarding&quot;                   &quot;0&quot;  
## [15,] &quot;Class&quot;                             &quot;0&quot;  
## [16,] &quot;DepartureDelayin_Mins&quot;             &quot;0&quot;  
## [17,] &quot;Satisfaction&quot;                      &quot;0&quot;  
## [18,] &quot;CustomerType_loyal_customer&quot;       &quot;0&quot;  
## [19,] &quot;TypeTravel_personal_travel&quot;        &quot;0&quot;  
## [20,] &quot;Age_X_20_25_&quot;                      &quot;0&quot;  
## [21,] &quot;Age_X_25_30_&quot;                      &quot;0&quot;  
## [22,] &quot;Age_X_30_35_&quot;                      &quot;0&quot;  
## [23,] &quot;Age_X_35_40_&quot;                      &quot;0&quot;  
## [24,] &quot;Age_X_40_45_&quot;                      &quot;0&quot;  
## [25,] &quot;Age_X_45_50_&quot;                      &quot;0&quot;  
## [26,] &quot;Age_X_50_55_&quot;                      &quot;0&quot;  
## [27,] &quot;Age_X_55_60_&quot;                      &quot;0&quot;  
## [28,] &quot;Age_X_60_65_&quot;                      &quot;0&quot;  
## [29,] &quot;Age_X_65_above_&quot;                   &quot;0&quot;
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Check null proportion for each variable.</span>
df_test_processed <span class="o">%&gt;%</span> 
    summarise_all<span class="p">(</span><span class="o">~</span> <span class="kp">sum</span><span class="p">(</span><span class="kp">is.na</span><span class="p">(</span><span class="m">.</span><span class="p">))</span> <span class="o">/</span> <span class="kp">length</span><span class="p">(</span><span class="m">.</span><span class="p">)</span> <span class="o">*</span> <span class="m">100</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    gather<span class="p">()</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       key                                 value
##  [1,] &quot;Gate_location&quot;                     &quot;0&quot;  
##  [2,] &quot;Seat_comfort&quot;                      &quot;0&quot;  
##  [3,] &quot;Departure_Arrival_time_convenient&quot; &quot;0&quot;  
##  [4,] &quot;Food_drink&quot;                        &quot;0&quot;  
##  [5,] &quot;Inflightwifi_service&quot;              &quot;0&quot;  
##  [6,] &quot;Inflight_entertainment&quot;            &quot;0&quot;  
##  [7,] &quot;Online_support&quot;                    &quot;0&quot;  
##  [8,] &quot;Ease_of_Onlinebooking&quot;             &quot;0&quot;  
##  [9,] &quot;Onboard_service&quot;                   &quot;0&quot;  
## [10,] &quot;Leg_room_service&quot;                  &quot;0&quot;  
## [11,] &quot;Baggage_handling&quot;                  &quot;0&quot;  
## [12,] &quot;Checkin_service&quot;                   &quot;0&quot;  
## [13,] &quot;Cleanliness&quot;                       &quot;0&quot;  
## [14,] &quot;Online_boarding&quot;                   &quot;0&quot;  
## [15,] &quot;Class&quot;                             &quot;0&quot;  
## [16,] &quot;DepartureDelayin_Mins&quot;             &quot;0&quot;  
## [17,] &quot;Satisfaction&quot;                      &quot;0&quot;  
## [18,] &quot;CustomerType_loyal_customer&quot;       &quot;0&quot;  
## [19,] &quot;TypeTravel_personal_travel&quot;        &quot;0&quot;  
## [20,] &quot;Age_X_20_25_&quot;                      &quot;0&quot;  
## [21,] &quot;Age_X_25_30_&quot;                      &quot;0&quot;  
## [22,] &quot;Age_X_30_35_&quot;                      &quot;0&quot;  
## [23,] &quot;Age_X_35_40_&quot;                      &quot;0&quot;  
## [24,] &quot;Age_X_40_45_&quot;                      &quot;0&quot;  
## [25,] &quot;Age_X_45_50_&quot;                      &quot;0&quot;  
## [26,] &quot;Age_X_50_55_&quot;                      &quot;0&quot;  
## [27,] &quot;Age_X_55_60_&quot;                      &quot;0&quot;  
## [28,] &quot;Age_X_60_65_&quot;                      &quot;0&quot;  
## [29,] &quot;Age_X_65_above_&quot;                   &quot;0&quot;
</code></pre>

<h2 id="6-model-training-and-evaluation">6 Model training and evaluation.</h2>

<h3 id="6-1-train-logistic-model">6.1 Train Logistic model.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">model_log_glm <span class="o">=</span> logistic_reg<span class="p">(</span>mode<span class="o">=</span><span class="s">&#34;classification&#34;</span><span class="p">,</span> penalty<span class="o">=</span><span class="kc">NULL</span><span class="p">,</span> mixture<span class="o">=</span><span class="kc">NULL</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    set_engine<span class="p">(</span><span class="s">&#34;glm&#34;</span><span class="p">)</span> <span class="o">%&gt;%</span>
    fit<span class="p">(</span>Satisfaction <span class="o">~</span> <span class="m">.</span><span class="p">,</span> data<span class="o">=</span>df_train_processed<span class="p">)</span>

<span class="c1"># Sort the important variables in descending order. </span>
broom<span class="o">::</span>tidy<span class="p">(</span>model_log_glm<span class="p">)</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>estimate_abs <span class="o">=</span> <span class="kp">abs</span><span class="p">(</span>estimate<span class="p">))</span> <span class="o">%&gt;%</span> 
    arrange<span class="p">(</span>desc<span class="p">(</span>estimate_abs<span class="p">))</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       term                                estimate        std.error   
##  [1,] &quot;(Intercept)&quot;                       &quot;-11.476577680&quot; &quot;0.15918237&quot;
##  [2,] &quot;CustomerType_loyal_customer&quot;       &quot;  2.023262347&quot; &quot;0.03809987&quot;
##  [3,] &quot;TypeTravel_personal_travel&quot;        &quot; -0.763665758&quot; &quot;0.03478061&quot;
##  [4,] &quot;Inflight_entertainment&quot;            &quot;  0.713533661&quot; &quot;0.01227181&quot;
##  [5,] &quot;Age_X_20_25_&quot;                      &quot;  0.604837365&quot; &quot;0.11856182&quot;
##  [6,] &quot;Class&quot;                             &quot;  0.349075526&quot; &quot;0.01560330&quot;
##  [7,] &quot;Age_X_65_above_&quot;                   &quot; -0.342270381&quot; &quot;0.12275670&quot;
##  [8,] &quot;Onboard_service&quot;                   &quot;  0.307492901&quot; &quot;0.01238978&quot;
##  [9,] &quot;Checkin_service&quot;                   &quot;  0.298093320&quot; &quot;0.01027447&quot;
## [10,] &quot;Seat_comfort&quot;                      &quot;  0.293433924&quot; &quot;0.01375993&quot;
## [11,] &quot;Leg_room_service&quot;                  &quot;  0.244499369&quot; &quot;0.01048993&quot;
## [12,] &quot;Ease_of_Onlinebooking&quot;             &quot;  0.227079970&quot; &quot;0.01712689&quot;
## [13,] &quot;Departure_Arrival_time_convenient&quot; &quot; -0.223489943&quot; &quot;0.01024430&quot;
## [14,] &quot;Food_drink&quot;                        &quot; -0.193568741&quot; &quot;0.01414826&quot;
## [15,] &quot;DepartureDelayin_Mins&quot;             &quot; -0.181473436&quot; &quot;0.01182124&quot;
## [16,] &quot;Online_boarding&quot;                   &quot;  0.159139122&quot; &quot;0.01445829&quot;
## [17,] &quot;Age_X_35_40_&quot;                      &quot; -0.149635269&quot; &quot;0.11763886&quot;
## [18,] &quot;Age_X_30_35_&quot;                      &quot; -0.135231098&quot; &quot;0.11907163&quot;
## [19,] &quot;Gate_location&quot;                     &quot;  0.128356698&quot; &quot;0.01142551&quot;
## [20,] &quot;Age_X_40_45_&quot;                      &quot;  0.119893498&quot; &quot;0.11800470&quot;
## [21,] &quot;Age_X_60_65_&quot;                      &quot; -0.118723095&quot; &quot;0.12321060&quot;
## [22,] &quot;Age_X_55_60_&quot;                      &quot;  0.100678631&quot; &quot;0.12004056&quot;
## [23,] &quot;Online_support&quot;                    &quot;  0.098306492&quot; &quot;0.01327609&quot;
## [24,] &quot;Baggage_handling&quot;                  &quot;  0.093318919&quot; &quot;0.01388335&quot;
## [25,] &quot;Cleanliness&quot;                       &quot;  0.093218231&quot; &quot;0.01449605&quot;
## [26,] &quot;Inflightwifi_service&quot;              &quot; -0.065751043&quot; &quot;0.01288318&quot;
## [27,] &quot;Age_X_45_50_&quot;                      &quot;  0.029825331&quot; &quot;0.11847877&quot;
## [28,] &quot;Age_X_50_55_&quot;                      &quot;  0.016144614&quot; &quot;0.11919288&quot;
## [29,] &quot;Age_X_25_30_&quot;                      &quot;  0.006496901&quot; &quot;0.11802736&quot;
##       statistic      p.value         estimate_abs  
##  [1,] &quot;-72.09704018&quot; &quot; 0.000000e+00&quot; &quot;11.476577680&quot;
##  [2,] &quot; 53.10418459&quot; &quot; 0.000000e+00&quot; &quot; 2.023262347&quot;
##  [3,] &quot;-21.95665126&quot; &quot;7.481345e-107&quot; &quot; 0.763665758&quot;
##  [4,] &quot; 58.14412491&quot; &quot; 0.000000e+00&quot; &quot; 0.713533661&quot;
##  [5,] &quot;  5.10145129&quot; &quot; 3.370588e-07&quot; &quot; 0.604837365&quot;
##  [6,] &quot; 22.37190085&quot; &quot;7.391911e-111&quot; &quot; 0.349075526&quot;
##  [7,] &quot; -2.78820128&quot; &quot; 5.300160e-03&quot; &quot; 0.342270381&quot;
##  [8,] &quot; 24.81827407&quot; &quot;5.692902e-136&quot; &quot; 0.307492901&quot;
##  [9,] &quot; 29.01300467&quot; &quot;4.510022e-185&quot; &quot; 0.298093320&quot;
## [10,] &quot; 21.32524085&quot; &quot;6.621196e-101&quot; &quot; 0.293433924&quot;
## [11,] &quot; 23.30800929&quot; &quot;3.677164e-120&quot; &quot; 0.244499369&quot;
## [12,] &quot; 13.25868114&quot; &quot; 4.019016e-40&quot; &quot; 0.227079970&quot;
## [13,] &quot;-21.81602471&quot; &quot;1.634671e-105&quot; &quot; 0.223489943&quot;
## [14,] &quot;-13.68145428&quot; &quot; 1.310453e-42&quot; &quot; 0.193568741&quot;
## [15,] &quot;-15.35147320&quot; &quot; 3.462335e-53&quot; &quot; 0.181473436&quot;
## [16,] &quot; 11.00677619&quot; &quot; 3.544612e-28&quot; &quot; 0.159139122&quot;
## [17,] &quot; -1.27198845&quot; &quot; 2.033772e-01&quot; &quot; 0.149635269&quot;
## [18,] &quot; -1.13571221&quot; &quot; 2.560770e-01&quot; &quot; 0.135231098&quot;
## [19,] &quot; 11.23421912&quot; &quot; 2.769315e-29&quot; &quot; 0.128356698&quot;
## [20,] &quot;  1.01600617&quot; &quot; 3.096264e-01&quot; &quot; 0.119893498&quot;
## [21,] &quot; -0.96357860&quot; &quot; 3.352572e-01&quot; &quot; 0.118723095&quot;
## [22,] &quot;  0.83870510&quot; &quot; 4.016348e-01&quot; &quot; 0.100678631&quot;
## [23,] &quot;  7.40477835&quot; &quot; 1.313697e-13&quot; &quot; 0.098306492&quot;
## [24,] &quot;  6.72164424&quot; &quot; 1.796852e-11&quot; &quot; 0.093318919&quot;
## [25,] &quot;  6.43059380&quot; &quot; 1.271064e-10&quot; &quot; 0.093218231&quot;
## [26,] &quot; -5.10363358&quot; &quot; 3.331931e-07&quot; &quot; 0.065751043&quot;
## [27,] &quot;  0.25173567&quot; &quot; 8.012454e-01&quot; &quot; 0.029825331&quot;
## [28,] &quot;  0.13544949&quot; &quot; 8.922565e-01&quot; &quot; 0.016144614&quot;
## [29,] &quot;  0.05504572&quot; &quot; 9.561020e-01&quot; &quot; 0.006496901&quot;
</code></pre>

<hr />

<h4 id="6-1-1-adjust-the-model-parameter">6.1.1 Adjust the model parameter.</h4>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Adjust the model parameter.  </span>
model_log_glm_adjusted <span class="o">=</span> MASS<span class="o">::</span>stepAIC<span class="p">(</span>stats<span class="o">::</span>glm<span class="p">(</span>Satisfaction <span class="o">~</span> <span class="m">.</span><span class="p">,</span> 
                                                  family<span class="o">=</span>stats<span class="o">::</span>binomial<span class="p">,</span> 
                                                  data<span class="o">=</span>df_train_processed<span class="p">),</span> 
                                       direction<span class="o">=</span><span class="s">&#34;both&#34;</span><span class="p">,</span> k<span class="o">=</span><span class="m">21</span><span class="p">)</span></code></pre></div>
<pre><code>## Start:  AIC=46019.71
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_25_30_ + 
##     Age_X_30_35_ + Age_X_35_40_ + Age_X_40_45_ + Age_X_45_50_ + 
##     Age_X_50_55_ + Age_X_55_60_ + Age_X_60_65_ + Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_25_30_                       1    45411 45999
## - Age_X_50_55_                       1    45411 45999
## - Age_X_45_50_                       1    45411 45999
## - Age_X_55_60_                       1    45411 45999
## - Age_X_60_65_                       1    45412 46000
## - Age_X_40_45_                       1    45412 46000
## - Age_X_30_35_                       1    45412 46000
## - Age_X_35_40_                       1    45412 46000
## - Age_X_65_above_                    1    45418 46006
## &lt;none&gt;                                    45411 46020
## - Age_X_20_25_                       1    45437 46025
## - Inflightwifi_service               1    45437 46025
## - Cleanliness                        1    45452 46040
## - Baggage_handling                   1    45456 46044
## - Online_support                     1    45465 46053
## - Online_boarding                    1    45532 46120
## - Gate_location                      1    45537 46125
## - Ease_of_Onlinebooking              1    45587 46175
## - Food_drink                         1    45599 46187
## - DepartureDelayin_Mins              1    45648 46236
## - Seat_comfort                       1    45874 46462
## - TypeTravel_personal_travel         1    45896 46484
## - Departure_Arrival_time_convenient  1    45896 46484
## - Class                              1    45916 46504
## - Leg_room_service                   1    45956 46544
## - Onboard_service                    1    46037 46625
## - Checkin_service                    1    46273 46861
## - CustomerType_loyal_customer        1    48524 49112
## - Inflight_entertainment             1    49154 49742
## 
## Step:  AIC=45998.72
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_30_35_ + 
##     Age_X_35_40_ + Age_X_40_45_ + Age_X_45_50_ + Age_X_50_55_ + 
##     Age_X_55_60_ + Age_X_60_65_ + Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_50_55_                       1    45411 45978
## - Age_X_45_50_                       1    45411 45978
## - Age_X_55_60_                       1    45414 45981
## - Age_X_60_65_                       1    45415 45982
## - Age_X_40_45_                       1    45416 45983
## - Age_X_30_35_                       1    45418 45985
## - Age_X_35_40_                       1    45422 45989
## &lt;none&gt;                                    45411 45999
## - Inflightwifi_service               1    45437 46004
## - Age_X_65_above_                    1    45444 46011
## - Cleanliness                        1    45452 46019
## + Age_X_25_30_                       1    45411 46020
## - Baggage_handling                   1    45456 46023
## - Online_support                     1    45465 46032
## - Online_boarding                    1    45532 46099
## - Gate_location                      1    45537 46104
## - Age_X_20_25_                       1    45564 46131
## - Ease_of_Onlinebooking              1    45587 46154
## - Food_drink                         1    45599 46166
## - DepartureDelayin_Mins              1    45648 46215
## - Seat_comfort                       1    45874 46441
## - Departure_Arrival_time_convenient  1    45896 46463
## - TypeTravel_personal_travel         1    45896 46463
## - Class                              1    45916 46483
## - Leg_room_service                   1    45956 46523
## - Onboard_service                    1    46037 46604
## - Checkin_service                    1    46273 46840
## - CustomerType_loyal_customer        1    48530 49097
## - Inflight_entertainment             1    49154 49721
## 
## Step:  AIC=45977.76
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_30_35_ + 
##     Age_X_35_40_ + Age_X_40_45_ + Age_X_45_50_ + Age_X_55_60_ + 
##     Age_X_60_65_ + Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_45_50_                       1    45411 45957
## - Age_X_55_60_                       1    45414 45960
## - Age_X_60_65_                       1    45416 45962
## - Age_X_40_45_                       1    45417 45963
## - Age_X_30_35_                       1    45421 45967
## - Age_X_35_40_                       1    45426 45972
## &lt;none&gt;                                    45411 45978
## - Inflightwifi_service               1    45437 45983
## - Age_X_65_above_                    1    45451 45997
## - Cleanliness                        1    45452 45998
## + Age_X_50_55_                       1    45411 45999
## + Age_X_25_30_                       1    45411 45999
## - Baggage_handling                   1    45456 46002
## - Online_support                     1    45466 46012
## - Online_boarding                    1    45532 46078
## - Gate_location                      1    45538 46084
## - Ease_of_Onlinebooking              1    45587 46133
## - Age_X_20_25_                       1    45592 46138
## - Food_drink                         1    45600 46146
## - DepartureDelayin_Mins              1    45648 46194
## - Seat_comfort                       1    45874 46420
## - Departure_Arrival_time_convenient  1    45896 46442
## - TypeTravel_personal_travel         1    45898 46444
## - Class                              1    45916 46462
## - Leg_room_service                   1    45956 46502
## - Onboard_service                    1    46037 46583
## - Checkin_service                    1    46273 46819
## - CustomerType_loyal_customer        1    48681 49227
## - Inflight_entertainment             1    49159 49705
## 
## Step:  AIC=45956.95
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_30_35_ + 
##     Age_X_35_40_ + Age_X_40_45_ + Age_X_55_60_ + Age_X_60_65_ + 
##     Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_55_60_                       1    45414 45939
## - Age_X_60_65_                       1    45417 45942
## - Age_X_40_45_                       1    45418 45943
## - Age_X_30_35_                       1    45423 45948
## - Age_X_35_40_                       1    45429 45954
## &lt;none&gt;                                    45411 45957
## - Inflightwifi_service               1    45437 45962
## - Cleanliness                        1    45452 45977
## + Age_X_45_50_                       1    45411 45978
## + Age_X_25_30_                       1    45411 45978
## + Age_X_50_55_                       1    45411 45978
## - Baggage_handling                   1    45456 45981
## - Age_X_65_above_                    1    45456 45981
## - Online_support                     1    45466 45991
## - Online_boarding                    1    45532 46057
## - Gate_location                      1    45538 46063
## - Ease_of_Onlinebooking              1    45587 46112
## - Food_drink                         1    45600 46125
## - Age_X_20_25_                       1    45605 46130
## - DepartureDelayin_Mins              1    45648 46173
## - Seat_comfort                       1    45874 46399
## - Departure_Arrival_time_convenient  1    45896 46421
## - TypeTravel_personal_travel         1    45900 46425
## - Class                              1    45917 46442
## - Leg_room_service                   1    45957 46482
## - Onboard_service                    1    46038 46563
## - Checkin_service                    1    46273 46798
## - CustomerType_loyal_customer        1    48735 49260
## - Inflight_entertainment             1    49161 49686
## 
## Step:  AIC=45939.31
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_30_35_ + 
##     Age_X_35_40_ + Age_X_40_45_ + Age_X_60_65_ + Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_40_45_                       1    45419 45923
## - Age_X_60_65_                       1    45423 45927
## - Age_X_30_35_                       1    45430 45934
## &lt;none&gt;                                    45414 45939
## - Age_X_35_40_                       1    45438 45942
## - Inflightwifi_service               1    45441 45945
## + Age_X_55_60_                       1    45411 45957
## - Cleanliness                        1    45455 45959
## + Age_X_25_30_                       1    45414 45960
## + Age_X_50_55_                       1    45414 45960
## + Age_X_45_50_                       1    45414 45960
## - Baggage_handling                   1    45459 45963
## - Age_X_65_above_                    1    45466 45970
## - Online_support                     1    45470 45974
## - Online_boarding                    1    45535 46039
## - Gate_location                      1    45541 46045
## - Ease_of_Onlinebooking              1    45590 46094
## - Food_drink                         1    45603 46107
## - Age_X_20_25_                       1    45606 46110
## - DepartureDelayin_Mins              1    45651 46155
## - Seat_comfort                       1    45877 46381
## - Departure_Arrival_time_convenient  1    45899 46403
## - TypeTravel_personal_travel         1    45904 46408
## - Class                              1    45919 46423
## - Leg_room_service                   1    45962 46466
## - Onboard_service                    1    46043 46547
## - Checkin_service                    1    46276 46780
## - CustomerType_loyal_customer        1    48785 49289
## - Inflight_entertainment             1    49167 49671
## 
## Step:  AIC=45923.28
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_30_35_ + 
##     Age_X_35_40_ + Age_X_60_65_ + Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_60_65_                       1    45430 45913
## - Age_X_30_35_                       1    45440 45923
## &lt;none&gt;                                    45419 45923
## - Inflightwifi_service               1    45446 45929
## - Age_X_35_40_                       1    45449 45932
## + Age_X_40_45_                       1    45414 45939
## + Age_X_25_30_                       1    45417 45942
## + Age_X_55_60_                       1    45418 45943
## + Age_X_50_55_                       1    45418 45943
## - Cleanliness                        1    45460 45943
## + Age_X_45_50_                       1    45419 45944
## - Baggage_handling                   1    45464 45947
## - Online_support                     1    45476 45959
## - Age_X_65_above_                    1    45478 45961
## - Online_boarding                    1    45540 46023
## - Gate_location                      1    45546 46029
## - Ease_of_Onlinebooking              1    45595 46078
## - Age_X_20_25_                       1    45606 46089
## - Food_drink                         1    45609 46092
## - DepartureDelayin_Mins              1    45656 46139
## - Seat_comfort                       1    45882 46365
## - Departure_Arrival_time_convenient  1    45903 46386
## - TypeTravel_personal_travel         1    45914 46397
## - Class                              1    45923 46406
## - Leg_room_service                   1    45967 46450
## - Onboard_service                    1    46048 46531
## - Checkin_service                    1    46280 46763
## - CustomerType_loyal_customer        1    48806 49289
## - Inflight_entertainment             1    49173 49656
## 
## Step:  AIC=45912.93
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_30_35_ + 
##     Age_X_35_40_ + Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_30_35_                       1    45447 45909
## &lt;none&gt;                                    45430 45913
## - Inflightwifi_service               1    45456 45918
## - Age_X_35_40_                       1    45456 45918
## + Age_X_60_65_                       1    45419 45923
## + Age_X_40_45_                       1    45423 45927
## + Age_X_55_60_                       1    45427 45931
## + Age_X_25_30_                       1    45429 45933
## - Cleanliness                        1    45471 45933
## + Age_X_50_55_                       1    45430 45934
## + Age_X_45_50_                       1    45430 45934
## - Baggage_handling                   1    45475 45937
## - Age_X_65_above_                    1    45483 45945
## - Online_support                     1    45486 45948
## - Online_boarding                    1    45551 46013
## - Gate_location                      1    45557 46019
## - Ease_of_Onlinebooking              1    45605 46067
## - Food_drink                         1    45620 46082
## - Age_X_20_25_                       1    45629 46091
## - DepartureDelayin_Mins              1    45667 46129
## - Seat_comfort                       1    45894 46356
## - Departure_Arrival_time_convenient  1    45914 46376
## - Class                              1    45937 46399
## - TypeTravel_personal_travel         1    45939 46401
## - Leg_room_service                   1    45977 46439
## - Onboard_service                    1    46059 46521
## - Checkin_service                    1    46293 46755
## - CustomerType_loyal_customer        1    48809 49271
## - Inflight_entertainment             1    49187 49649
## 
## Step:  AIC=45909.49
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_35_40_ + 
##     Age_X_65_above_
## 
##                                     Df Deviance   AIC
## - Age_X_35_40_                       1    45468 45909
## &lt;none&gt;                                    45447 45909
## + Age_X_30_35_                       1    45430 45913
## - Inflightwifi_service               1    45473 45914
## + Age_X_40_45_                       1    45436 45919
## + Age_X_60_65_                       1    45440 45923
## + Age_X_55_60_                       1    45442 45925
## - Cleanliness                        1    45487 45928
## + Age_X_45_50_                       1    45447 45930
## + Age_X_25_30_                       1    45447 45930
## + Age_X_50_55_                       1    45447 45930
## - Baggage_handling                   1    45492 45933
## - Age_X_65_above_                    1    45495 45936
## - Online_support                     1    45505 45946
## - Online_boarding                    1    45567 46008
## - Gate_location                      1    45575 46016
## - Ease_of_Onlinebooking              1    45622 46063
## - Food_drink                         1    45638 46079
## - Age_X_20_25_                       1    45668 46109
## - DepartureDelayin_Mins              1    45685 46126
## - Seat_comfort                       1    45910 46351
## - Departure_Arrival_time_convenient  1    45930 46371
## - Class                              1    45949 46390
## - TypeTravel_personal_travel         1    45960 46401
## - Leg_room_service                   1    45999 46440
## - Onboard_service                    1    46082 46523
## - Checkin_service                    1    46311 46752
## - CustomerType_loyal_customer        1    48831 49272
## - Inflight_entertainment             1    49228 49669
## 
## Step:  AIC=45908.97
## Satisfaction ~ Gate_location + Seat_comfort + Departure_Arrival_time_convenient + 
##     Food_drink + Inflightwifi_service + Inflight_entertainment + 
##     Online_support + Ease_of_Onlinebooking + Onboard_service + 
##     Leg_room_service + Baggage_handling + Checkin_service + Cleanliness + 
##     Online_boarding + Class + DepartureDelayin_Mins + CustomerType_loyal_customer + 
##     TypeTravel_personal_travel + Age_X_20_25_ + Age_X_65_above_
## 
##                                     Df Deviance   AIC
## &lt;none&gt;                                    45468 45909
## + Age_X_35_40_                       1    45447 45909
## + Age_X_40_45_                       1    45450 45912
## - Inflightwifi_service               1    45494 45914
## + Age_X_30_35_                       1    45456 45918
## + Age_X_55_60_                       1    45460 45922
## + Age_X_60_65_                       1    45463 45925
## - Cleanliness                        1    45508 45928
## + Age_X_45_50_                       1    45466 45928
## + Age_X_25_30_                       1    45467 45929
## + Age_X_50_55_                       1    45467 45929
## - Age_X_65_above_                    1    45510 45930
## - Baggage_handling                   1    45513 45933
## - Online_support                     1    45526 45946
## - Online_boarding                    1    45589 46009
## - Gate_location                      1    45595 46015
## - Ease_of_Onlinebooking              1    45641 46061
## - Food_drink                         1    45655 46075
## - DepartureDelayin_Mins              1    45704 46124
## - Age_X_20_25_                       1    45717 46137
## - Seat_comfort                       1    45926 46346
## - Departure_Arrival_time_convenient  1    45952 46372
## - Class                              1    45969 46389
## - TypeTravel_personal_travel         1    45977 46397
## - Leg_room_service                   1    46021 46441
## - Onboard_service                    1    46102 46522
## - Checkin_service                    1    46334 46754
## - CustomerType_loyal_customer        1    48916 49336
## - Inflight_entertainment             1    49252 49672
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Check multi-collinearity issue. </span>
car<span class="o">::</span>vif<span class="p">(</span>model_log_glm_adjusted<span class="p">)</span> <span class="o">%&gt;%</span> 
    enframe<span class="p">()</span> <span class="o">%&gt;%</span> 
    arrange<span class="p">(</span>desc<span class="p">(</span>value<span class="p">))</span></code></pre></div>
<pre><code>## # A tibble: 20 x 2
##    name                              value
##    &lt;chr&gt;                             &lt;dbl&gt;
##  1 Ease_of_Onlinebooking              3.12
##  2 Food_drink                         2.83
##  3 Online_boarding                    2.35
##  4 Seat_comfort                       2.31
##  5 Cleanliness                        1.99
##  6 Inflightwifi_service               1.97
##  7 Online_support                     1.93
##  8 TypeTravel_personal_travel         1.92
##  9 Baggage_handling                   1.84
## 10 Departure_Arrival_time_convenient  1.79
## 11 Onboard_service                    1.63
## 12 Class                              1.60
## 13 Gate_location                      1.60
## 14 Inflight_entertainment             1.49
## 15 CustomerType_loyal_customer        1.47
## 16 Leg_room_service                   1.24
## 17 Checkin_service                    1.17
## 18 Age_X_20_25_                       1.15
## 19 Age_X_65_above_                    1.04
## 20 DepartureDelayin_Mins              1.01
</code></pre>

<hr />

<p>The table below shows the feature weights from the <code>Logistic</code> model
after checking the VIF and adjusting the parameters with <code>StepAIC</code> by
removing or adding the parameters to get the lowest AIC.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Finalised model. </span>
<span class="c1"># Preview the variable weights. </span>
broom<span class="o">::</span>tidy<span class="p">(</span>model_log_glm_adjusted<span class="p">)</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>estimate_abs <span class="o">=</span> <span class="kp">abs</span><span class="p">(</span>estimate<span class="p">))</span> <span class="o">%&gt;%</span> 
    arrange<span class="p">(</span>desc<span class="p">(</span>estimate_abs<span class="p">))</span> <span class="o">%&gt;%</span> 
    select<span class="p">(</span>term<span class="p">,</span> estimate<span class="p">)</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>estimate <span class="o">=</span> <span class="kp">round</span><span class="p">(</span>estimate<span class="p">,</span> <span class="m">4</span><span class="p">))</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       term                                estimate  
##  [1,] &quot;(Intercept)&quot;                       &quot;-11.5219&quot;
##  [2,] &quot;CustomerType_loyal_customer&quot;       &quot;  2.0452&quot;
##  [3,] &quot;TypeTravel_personal_travel&quot;        &quot; -0.7768&quot;
##  [4,] &quot;Inflight_entertainment&quot;            &quot;  0.7158&quot;
##  [5,] &quot;Age_X_20_25_&quot;                      &quot;  0.6252&quot;
##  [6,] &quot;Class&quot;                             &quot;  0.3470&quot;
##  [7,] &quot;Age_X_65_above_&quot;                   &quot; -0.3296&quot;
##  [8,] &quot;Onboard_service&quot;                   &quot;  0.3095&quot;
##  [9,] &quot;Checkin_service&quot;                   &quot;  0.2986&quot;
## [10,] &quot;Seat_comfort&quot;                      &quot;  0.2916&quot;
## [11,] &quot;Leg_room_service&quot;                  &quot;  0.2462&quot;
## [12,] &quot;Ease_of_Onlinebooking&quot;             &quot;  0.2250&quot;
## [13,] &quot;Departure_Arrival_time_convenient&quot; &quot; -0.2233&quot;
## [14,] &quot;Food_drink&quot;                        &quot; -0.1926&quot;
## [15,] &quot;DepartureDelayin_Mins&quot;             &quot; -0.1810&quot;
## [16,] &quot;Online_boarding&quot;                   &quot;  0.1587&quot;
## [17,] &quot;Gate_location&quot;                     &quot;  0.1285&quot;
## [18,] &quot;Online_support&quot;                    &quot;  0.1010&quot;
## [19,] &quot;Baggage_handling&quot;                  &quot;  0.0934&quot;
## [20,] &quot;Cleanliness&quot;                       &quot;  0.0917&quot;
## [21,] &quot;Inflightwifi_service&quot;              &quot; -0.0651&quot;
</code></pre>

<hr />

<h4 id="6-1-2-evaluate-the-model-performance">6.1.2 Evaluate the model performance.</h4>

<p>Compare the train and test result to see if it’s overfitting.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Train. </span>
model_train_performance <span class="o">=</span> df_train_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_log_glm_adjusted<span class="p">,</span> <span class="s">&#39;Model GLM Logistic&#39;</span><span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;response&#39;</span><span class="p">)</span>

model_train_performance</code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   model              accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                 &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model GLM Logistic    0.833  0.811 0.661     0.814   0.907 0.809
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Test.</span>
model_test_performance <span class="o">=</span> df_test_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_log_glm_adjusted<span class="p">,</span> <span class="s">&#39;Model GLM Logistic&#39;</span><span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;response&#39;</span><span class="p">)</span>

model_test_performance</code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   model              accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                 &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model GLM Logistic    0.832  0.809 0.660     0.804   0.906 0.815
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># View the confusion matrix.</span>
df_test_processed <span class="o">%&gt;%</span> 
    make_prediction<span class="p">(</span>model_log_glm_adjusted<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;response&#39;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    conf_matrix_result<span class="p">()</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction     0     1
##          0  8861  2162
##          1  2011 11878
##                                           
##                Accuracy : 0.8325          
##                  95% CI : (0.8278, 0.8371)
##     No Information Rate : 0.5636          
##     P-Value [Acc &gt; NIR] : &lt; 2e-16         
##                                           
##                   Kappa : 0.66            
##                                           
##  Mcnemar's Test P-Value : 0.02023         
##                                           
##             Sensitivity : 0.8460          
##             Specificity : 0.8150          
##          Pos Pred Value : 0.8552          
##          Neg Pred Value : 0.8039          
##              Prevalence : 0.5636          
##          Detection Rate : 0.4768          
##    Detection Prevalence : 0.5575          
##       Balanced Accuracy : 0.8305          
##                                           
##        'Positive' Class : 1               
## 
</code></pre>

<hr />

<h3 id="6-2-train-decision-tree-model">6.2 Train Decision Tree model.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="kp">set.seed</span><span class="p">(</span><span class="m">5</span><span class="p">)</span>
model_tree_decision <span class="o">=</span> decision_tree<span class="p">(</span>mode<span class="o">=</span><span class="s">&#34;classification&#34;</span><span class="p">,</span> cost_complexity<span class="o">=</span><span class="m">0</span><span class="p">,</span> 
                                    tree_depth<span class="o">=</span><span class="m">10</span><span class="p">,</span> min_n<span class="o">=</span><span class="m">50</span><span class="p">)</span> <span class="o">%&gt;%</span>
    set_engine<span class="p">(</span><span class="s">&#34;rpart&#34;</span><span class="p">)</span> <span class="o">%&gt;%</span>
    fit<span class="p">(</span>Satisfaction <span class="o">~</span> <span class="m">.</span><span class="p">,</span> data<span class="o">=</span>df_train_processed<span class="p">)</span>

printcp<span class="p">(</span>model_tree_decision<span class="o">$</span>fit<span class="p">)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart::rpart(formula = formula, data = data, cp = ~0, maxdepth = ~10, 
##     minsplit = ~50)
## 
## Variables actually used in tree construction:
##  [1] Age_X_20_25_                      Age_X_30_35_                     
##  [3] Age_X_55_60_                      Baggage_handling                 
##  [5] Checkin_service                   Class                            
##  [7] Cleanliness                       CustomerType_loyal_customer      
##  [9] Departure_Arrival_time_convenient DepartureDelayin_Mins            
## [11] Ease_of_Onlinebooking             Food_drink                       
## [13] Gate_location                     Inflight_entertainment           
## [15] Inflightwifi_service              Leg_room_service                 
## [17] Onboard_service                   Online_boarding                  
## [19] Online_support                    Seat_comfort                     
## [21] TypeTravel_personal_travel       
## 
## Root node error: 25854/58292 = 0.44353
## 
## n= 58292 
## 
##            CP nsplit rel error  xerror      xstd
## 1  5.5519e-01      0   1.00000 1.00000 0.0046394
## 2  5.3106e-02      1   0.44481 0.44481 0.0037162
## 3  4.2276e-02      2   0.39170 0.39170 0.0035381
## 4  1.1320e-02      3   0.34942 0.34942 0.0033795
## 5  9.7084e-03      6   0.31546 0.30251 0.0031829
## 6  4.5254e-03     10   0.26015 0.26015 0.0029835
## 7  4.3707e-03     11   0.25563 0.25779 0.0029717
## 8  4.0419e-03     12   0.25126 0.25358 0.0029504
## 9  3.1910e-03     14   0.24317 0.24317 0.0028968
## 10 2.4561e-03     16   0.23679 0.23679 0.0028630
## 11 2.3981e-03     18   0.23188 0.23138 0.0028339
## 12 2.0306e-03     19   0.22948 0.22503 0.0027992
## 13 1.7792e-03     22   0.22182 0.22194 0.0027820
## 14 1.6438e-03     23   0.22004 0.21939 0.0027677
## 15 1.3924e-03     25   0.21676 0.21795 0.0027596
## 16 1.3828e-03     26   0.21536 0.21416 0.0027380
## 17 1.3538e-03     30   0.20983 0.21238 0.0027278
## 18 1.2377e-03     33   0.20577 0.21033 0.0027160
## 19 1.1604e-03     34   0.20453 0.20786 0.0027016
## 20 1.0443e-03     35   0.20337 0.20716 0.0026975
## 21 1.0056e-03     37   0.20128 0.20268 0.0026711
## 22 9.4763e-04     41   0.19676 0.20090 0.0026605
## 23 8.3159e-04     45   0.19297 0.19687 0.0026363
## 24 8.1225e-04     51   0.18798 0.19115 0.0026013
## 25 7.7357e-04     53   0.18635 0.18864 0.0025857
## 26 7.5424e-04     55   0.18481 0.18751 0.0025787
## 27 7.3490e-04     57   0.18330 0.18709 0.0025760
## 28 6.9622e-04     59   0.18183 0.18643 0.0025719
## 29 6.7688e-04     63   0.17904 0.18330 0.0025521
## 30 6.1886e-04     65   0.17769 0.18272 0.0025484
## 31 5.8018e-04     70   0.17460 0.18051 0.0025344
## 32 5.6084e-04     74   0.17228 0.17800 0.0025182
## 33 5.2216e-04     77   0.17042 0.17680 0.0025104
## 34 5.0282e-04     79   0.16937 0.17556 0.0025024
## 35 4.6414e-04     82   0.16787 0.17541 0.0025013
## 36 4.4481e-04     84   0.16694 0.17425 0.0024938
## 37 3.8679e-04     86   0.16605 0.17282 0.0024843
## 38 3.6745e-04     89   0.16489 0.17096 0.0024721
## 39 3.4811e-04     91   0.16415 0.17084 0.0024713
## 40 3.3153e-04     93   0.16346 0.17081 0.0024710
## 41 3.0943e-04    100   0.16114 0.17007 0.0024662
## 42 2.7075e-04    102   0.16052 0.16941 0.0024618
## 43 2.3207e-04    107   0.15916 0.16957 0.0024628
## 44 1.9339e-04    113   0.15765 0.16872 0.0024571
## 45 1.5471e-04    114   0.15746 0.16856 0.0024561
## 46 1.3538e-04    117   0.15700 0.16864 0.0024566
## 47 1.1604e-04    119   0.15673 0.16810 0.0024530
## 48 1.0637e-04    123   0.15626 0.16829 0.0024543
## 49 7.7357e-05    127   0.15584 0.16833 0.0024545
## 50 6.4465e-05    128   0.15576 0.16829 0.0024543
## 51 5.8018e-05    131   0.15557 0.16868 0.0024569
## 52 0.0000e+00    137   0.15522 0.16922 0.0024605
</code></pre>

<hr />

<h4 id="6-2-1-prunning">6.2.1 Prunning.</h4>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Find the optimal CCP. </span>
plotcp<span class="p">(</span>model_tree_decision<span class="o">$</span>fit<span class="p">)</span></code></pre></div>
<p><img src="unnamed-chunk-31-1.png" style="display: block; margin: auto auto auto 0;" /></p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Prune the decision tree. </span>
model_tree_decision_pruned <span class="o">=</span> rpart<span class="o">::</span>prune<span class="p">(</span>model_tree_decision<span class="o">$</span>fit<span class="p">,</span> cp<span class="o">=</span><span class="m">7.5424e-04</span><span class="p">)</span>
printcp<span class="p">(</span>model_tree_decision_pruned<span class="p">)</span></code></pre></div>
<pre><code>## 
## Classification tree:
## rpart::rpart(formula = formula, data = data, cp = ~0, maxdepth = ~10, 
##     minsplit = ~50)
## 
## Variables actually used in tree construction:
##  [1] Baggage_handling                  Checkin_service                  
##  [3] Class                             Cleanliness                      
##  [5] CustomerType_loyal_customer       Departure_Arrival_time_convenient
##  [7] Ease_of_Onlinebooking             Food_drink                       
##  [9] Gate_location                     Inflight_entertainment           
## [11] Inflightwifi_service              Leg_room_service                 
## [13] Onboard_service                   Online_boarding                  
## [15] Online_support                    Seat_comfort                     
## [17] TypeTravel_personal_travel       
## 
## Root node error: 25854/58292 = 0.44353
## 
## n= 58292 
## 
##            CP nsplit rel error  xerror      xstd
## 1  0.55519455      0   1.00000 1.00000 0.0046394
## 2  0.05310590      1   0.44481 0.44481 0.0037162
## 3  0.04227586      2   0.39170 0.39170 0.0035381
## 4  0.01131998      3   0.34942 0.34942 0.0033795
## 5  0.00970836      6   0.31546 0.30251 0.0031829
## 6  0.00452541     10   0.26015 0.26015 0.0029835
## 7  0.00437070     11   0.25563 0.25779 0.0029717
## 8  0.00404193     12   0.25126 0.25358 0.0029504
## 9  0.00319100     14   0.24317 0.24317 0.0028968
## 10 0.00245610     16   0.23679 0.23679 0.0028630
## 11 0.00239808     18   0.23188 0.23138 0.0028339
## 12 0.00203063     19   0.22948 0.22503 0.0027992
## 13 0.00177922     22   0.22182 0.22194 0.0027820
## 14 0.00164385     23   0.22004 0.21939 0.0027677
## 15 0.00139243     25   0.21676 0.21795 0.0027596
## 16 0.00138276     26   0.21536 0.21416 0.0027380
## 17 0.00135376     30   0.20983 0.21238 0.0027278
## 18 0.00123772     33   0.20577 0.21033 0.0027160
## 19 0.00116036     34   0.20453 0.20786 0.0027016
## 20 0.00104433     35   0.20337 0.20716 0.0026975
## 21 0.00100565     37   0.20128 0.20268 0.0026711
## 22 0.00094763     41   0.19676 0.20090 0.0026605
## 23 0.00083159     45   0.19297 0.19687 0.0026363
## 24 0.00081225     51   0.18798 0.19115 0.0026013
## 25 0.00077357     53   0.18635 0.18864 0.0025857
## 26 0.00075424     55   0.18481 0.18751 0.0025787
</code></pre>

<hr />

<p>The table below shows the feature importance from <code>Decision Tree</code> after
executing the complexity pruning.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">model_tree_decision_pruned<span class="o">$</span>variable.importance <span class="o">%&gt;%</span> 
    <span class="kp">as.list</span><span class="p">()</span> <span class="o">%&gt;%</span> 
    as_tibble<span class="p">()</span> <span class="o">%&gt;%</span> 
    gather<span class="p">()</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       key                                 value         
##  [1,] &quot;Inflight_entertainment&quot;            &quot;11735.609799&quot;
##  [2,] &quot;Seat_comfort&quot;                      &quot; 7535.764335&quot;
##  [3,] &quot;Online_support&quot;                    &quot; 5539.098898&quot;
##  [4,] &quot;Ease_of_Onlinebooking&quot;             &quot; 4853.101183&quot;
##  [5,] &quot;Online_boarding&quot;                   &quot; 4023.785888&quot;
##  [6,] &quot;Checkin_service&quot;                   &quot; 2251.944064&quot;
##  [7,] &quot;Food_drink&quot;                        &quot; 1880.897415&quot;
##  [8,] &quot;CustomerType_loyal_customer&quot;       &quot; 1140.574469&quot;
##  [9,] &quot;Gate_location&quot;                     &quot;  898.829627&quot;
## [10,] &quot;Departure_Arrival_time_convenient&quot; &quot;  829.234110&quot;
## [11,] &quot;Cleanliness&quot;                       &quot;  819.898320&quot;
## [12,] &quot;Onboard_service&quot;                   &quot;  804.523078&quot;
## [13,] &quot;Inflightwifi_service&quot;              &quot;  646.378965&quot;
## [14,] &quot;Baggage_handling&quot;                  &quot;  631.533833&quot;
## [15,] &quot;Class&quot;                             &quot;  631.458653&quot;
## [16,] &quot;Leg_room_service&quot;                  &quot;  613.958893&quot;
## [17,] &quot;TypeTravel_personal_travel&quot;        &quot;  410.028850&quot;
## [18,] &quot;Age_X_20_25_&quot;                      &quot;   15.909620&quot;
## [19,] &quot;Age_X_65_above_&quot;                   &quot;   10.319077&quot;
## [20,] &quot;DepartureDelayin_Mins&quot;             &quot;    6.966611&quot;
## [21,] &quot;Age_X_60_65_&quot;                      &quot;    5.749491&quot;
## [22,] &quot;Age_X_35_40_&quot;                      &quot;    4.447313&quot;
## [23,] &quot;Age_X_25_30_&quot;                      &quot;    3.791678&quot;
## [24,] &quot;Age_X_45_50_&quot;                      &quot;    1.707423&quot;
## [25,] &quot;Age_X_30_35_&quot;                      &quot;    1.216308&quot;
</code></pre>

<hr />

<h4 id="6-2-2-evaluate-the-model-performance">6.2.2 Evaluate the model performance.</h4>

<p>Compare the train and test result to see if it’s overfitting.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Train. </span>
model_train_performance <span class="o">=</span> df_train_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_tree_decision_pruned<span class="p">,</span> <span class="s">&#39;Model Decision Tree&#39;</span><span class="p">,</span> 
                         model_train_performance<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;prob&#39;</span><span class="p">,</span> bind<span class="o">=</span><span class="kc">TRUE</span><span class="p">)</span>

model_train_performance</code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model Decision Tree    0.918  0.907 0.834     0.911   0.965 0.903
## 2 Model GLM Logistic     0.833  0.811 0.661     0.814   0.907 0.809
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Test. </span>
model_test_performance <span class="o">=</span> df_test_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_tree_decision_pruned<span class="p">,</span> <span class="s">&#39;Model Decision Tree&#39;</span><span class="p">,</span> 
                         model_test_performance<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;prob&#39;</span><span class="p">,</span> bind<span class="o">=</span><span class="kc">TRUE</span><span class="p">)</span>

model_test_performance</code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model Decision Tree    0.915  0.903 0.828     0.905   0.966 0.900
## 2 Model GLM Logistic     0.832  0.809 0.660     0.804   0.906 0.815
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># View the confusion matrix.</span>
df_test_processed <span class="o">%&gt;%</span> 
    make_prediction<span class="p">(</span>model_tree_decision_pruned<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;prob&#39;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    conf_matrix_result<span class="p">()</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction     0     1
##          0  9790  1025
##          1  1082 13015
##                                           
##                Accuracy : 0.9154          
##                  95% CI : (0.9119, 0.9188)
##     No Information Rate : 0.5636          
##     P-Value [Acc &gt; NIR] : &lt;2e-16          
##                                           
##                   Kappa : 0.828           
##                                           
##  Mcnemar's Test P-Value : 0.2225          
##                                           
##             Sensitivity : 0.9270          
##             Specificity : 0.9005          
##          Pos Pred Value : 0.9232          
##          Neg Pred Value : 0.9052          
##              Prevalence : 0.5636          
##          Detection Rate : 0.5224          
##    Detection Prevalence : 0.5659          
##       Balanced Accuracy : 0.9137          
##                                           
##        'Positive' Class : 1               
## 
</code></pre>

<hr />

<h3 id="6-3-train-random-forest-model">6.3 Train Random Forest model.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="kp">set.seed</span><span class="p">(</span><span class="m">5</span><span class="p">)</span>
model_random_forest <span class="o">=</span> rand_forest<span class="p">(</span><span class="s">&#34;classification&#34;</span><span class="p">,</span> trees<span class="o">=</span><span class="m">131</span><span class="p">,</span> mtry<span class="o">=</span><span class="m">5</span><span class="p">)</span> <span class="o">%&gt;%</span>
    set_engine<span class="p">(</span><span class="s">&#34;randomForest&#34;</span><span class="p">,</span> importance<span class="o">=</span><span class="kc">TRUE</span><span class="p">)</span> <span class="o">%&gt;%</span>
    fit<span class="p">(</span>Satisfaction <span class="o">~</span> <span class="m">.</span><span class="p">,</span> data<span class="o">=</span>df_train_processed<span class="p">)</span>

model_random_forest</code></pre></div>
<pre><code>## parsnip model object
## 
## Fit time:  1m 10.6s 
## 
## Call:
##  randomForest(x = as.data.frame(x), y = y, ntree = ~131, mtry = ~5,      importance = ~TRUE) 
##                Type of random forest: classification
##                      Number of trees: 131
## No. of variables tried at each split: 5
## 
##         OOB estimate of  error rate: 5.02%
## Confusion matrix:
##                         neutral_or dissatisfied satisfied class.error
## neutral_or dissatisfied                   24651      1203  0.04653052
## satisfied                                  1722     30716  0.05308589
</code></pre>

<h4 id="6-3-1-tune-the-model">6.3.1 Tune the model.</h4>

<p>This section took very long to run the tuning, so I directly input the
best parameters into the model, whenever I rerun the model training
section. The result below is a tuned model.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">plot<span class="p">(</span>model_random_forest<span class="o">$</span>fit<span class="p">,</span> main<span class="o">=</span><span class="s">&#34;Error Rates Random Forest&#34;</span><span class="p">)</span>
legend<span class="p">(</span><span class="s">&#34;topright&#34;</span><span class="p">,</span> legend<span class="o">=</span><span class="kt">c</span><span class="p">(</span><span class="s">&#34;OOB&#34;</span><span class="p">,</span> <span class="s">&#34;0&#34;</span><span class="p">,</span> <span class="s">&#34;1&#34;</span><span class="p">),</span> text.col<span class="o">=</span><span class="m">1</span><span class="o">:</span><span class="m">6</span><span class="p">,</span> lty<span class="o">=</span><span class="m">1</span><span class="o">:</span><span class="m">3</span><span class="p">,</span> col<span class="o">=</span><span class="m">1</span><span class="o">:</span><span class="m">3</span><span class="p">)</span> </code></pre></div>
<p><img src="unnamed-chunk-38-1.png" style="display: block; margin: auto auto auto 0;" /></p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># # I ran this previously. It took very long, so</span>
<span class="c1"># # I directly input the optimal &#39;mtry&#39; and &#39;trees&#39; into the model,</span>
<span class="c1"># # whenever I rerun the model training section.</span>
<span class="c1"># </span>
<span class="c1"># set.seed(5)</span>
<span class="c1"># model_random_forest_tuned = tuneRF(x=df_train_processed %&gt;% select(-Satisfaction),</span>
<span class="c1">#                                    y=df_train_processed$Satisfaction,</span>
<span class="c1">#                                    mtryStart=5, ntreeTry=131, stepFactor=1, improve=0.003,</span>
<span class="c1">#                                    trace=TRUE, plot=TRUE, doBest=TRUE, importance=TRUE)</span></code></pre></div>
<hr />

<p>The table below shows the feature importance for Random Forest.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Feature importance. </span>
model_random_forest<span class="o">$</span>fit<span class="o">$</span>importance <span class="o">%&gt;%</span> 
    as_tibble<span class="p">()</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>variables <span class="o">=</span> model_random_forest<span class="o">$</span>fit<span class="o">$</span>importance <span class="o">%&gt;%</span> <span class="kp">rownames</span><span class="p">())</span> <span class="o">%&gt;%</span> 
    select<span class="p">(</span>variables<span class="p">,</span> MeanDecreaseGini<span class="p">)</span> <span class="o">%&gt;%</span> 
    arrange<span class="p">(</span>desc<span class="p">(</span>MeanDecreaseGini<span class="p">))</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       variables                           MeanDecreaseGini
##  [1,] &quot;Inflight_entertainment&quot;            &quot;5476.96868&quot;    
##  [2,] &quot;Seat_comfort&quot;                      &quot;3714.97117&quot;    
##  [3,] &quot;Ease_of_Onlinebooking&quot;             &quot;2297.79968&quot;    
##  [4,] &quot;Online_support&quot;                    &quot;1867.25834&quot;    
##  [5,] &quot;Leg_room_service&quot;                  &quot;1528.80358&quot;    
##  [6,] &quot;CustomerType_loyal_customer&quot;       &quot;1426.87838&quot;    
##  [7,] &quot;Food_drink&quot;                        &quot;1319.23242&quot;    
##  [8,] &quot;Onboard_service&quot;                   &quot;1266.59573&quot;    
##  [9,] &quot;Class&quot;                             &quot;1213.71162&quot;    
## [10,] &quot;Online_boarding&quot;                   &quot;1192.80400&quot;    
## [11,] &quot;Baggage_handling&quot;                  &quot; 865.76560&quot;    
## [12,] &quot;Checkin_service&quot;                   &quot; 865.49995&quot;    
## [13,] &quot;Departure_Arrival_time_convenient&quot; &quot; 848.52265&quot;    
## [14,] &quot;Cleanliness&quot;                       &quot; 823.69312&quot;    
## [15,] &quot;Gate_location&quot;                     &quot; 709.22705&quot;    
## [16,] &quot;Inflightwifi_service&quot;              &quot; 634.67276&quot;    
## [17,] &quot;DepartureDelayin_Mins&quot;             &quot; 604.29593&quot;    
## [18,] &quot;TypeTravel_personal_travel&quot;        &quot; 586.88634&quot;    
## [19,] &quot;Age_X_20_25_&quot;                      &quot; 149.30125&quot;    
## [20,] &quot;Age_X_25_30_&quot;                      &quot; 125.38116&quot;    
## [21,] &quot;Age_X_35_40_&quot;                      &quot; 117.96141&quot;    
## [22,] &quot;Age_X_40_45_&quot;                      &quot; 107.63772&quot;    
## [23,] &quot;Age_X_30_35_&quot;                      &quot;  99.96445&quot;    
## [24,] &quot;Age_X_45_50_&quot;                      &quot;  95.17959&quot;    
## [25,] &quot;Age_X_65_above_&quot;                   &quot;  88.13647&quot;    
## [26,] &quot;Age_X_50_55_&quot;                      &quot;  87.85022&quot;    
## [27,] &quot;Age_X_55_60_&quot;                      &quot;  78.09450&quot;    
## [28,] &quot;Age_X_60_65_&quot;                      &quot;  69.62160&quot;
</code></pre>

<hr />

<h4 id="6-3-2-evaluate-the-model-performance">6.3.2 Evaluate the model performance.</h4>

<p>Compare the train and test result to see if it’s overfitting.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Train.</span>
model_train_performance <span class="o">=</span> df_train_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_random_forest<span class="p">,</span> <span class="s">&#39;Model Random Forest&#39;</span><span class="p">,</span> 
                         model_train_performance<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;ensemble&#39;</span><span class="p">,</span> bind<span class="o">=</span><span class="kc">TRUE</span><span class="p">)</span>

model_train_performance</code></pre></div>
<pre><code>## # A tibble: 3 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model Random Forest    0.999  0.999 0.998     0.998   1.00  0.999
## 2 Model Decision Tree    0.918  0.907 0.834     0.911   0.965 0.903
## 3 Model GLM Logistic     0.833  0.811 0.661     0.814   0.907 0.809
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Test.</span>
model_test_performance <span class="o">=</span> df_test_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_random_forest<span class="p">,</span> <span class="s">&#39;Model Random Forest&#39;</span><span class="p">,</span> 
                         model_test_performance<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;ensemble&#39;</span><span class="p">,</span> bind<span class="o">=</span><span class="kc">TRUE</span><span class="p">)</span>

model_test_performance</code></pre></div>
<pre><code>## # A tibble: 3 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model Random Forest    0.952  0.946 0.903     0.937   0.992 0.955
## 2 Model Decision Tree    0.915  0.903 0.828     0.905   0.966 0.900
## 3 Model GLM Logistic     0.832  0.809 0.660     0.804   0.906 0.815
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># View the confusion matrix.</span>
df_test_processed <span class="o">%&gt;%</span> 
    make_prediction<span class="p">(</span>model_random_forest<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;ensemble&#39;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    conf_matrix_result<span class="p">()</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction     0     1
##          0 10380   695
##          1   492 13345
##                                          
##                Accuracy : 0.9524         
##                  95% CI : (0.9496, 0.955)
##     No Information Rate : 0.5636         
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
##                                          
##                   Kappa : 0.9033         
##                                          
##  Mcnemar's Test P-Value : 4.544e-09      
##                                          
##             Sensitivity : 0.9505         
##             Specificity : 0.9547         
##          Pos Pred Value : 0.9644         
##          Neg Pred Value : 0.9372         
##              Prevalence : 0.5636         
##          Detection Rate : 0.5357         
##    Detection Prevalence : 0.5554         
##       Balanced Accuracy : 0.9526         
##                                          
##        'Positive' Class : 1              
## 
</code></pre>

<hr />

<h3 id="6-4-train-xgboost-model">6.4 Train XGBoost model.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">model_xgb <span class="o">=</span> boost_tree<span class="p">(</span>mode<span class="o">=</span><span class="s">&#34;classification&#34;</span><span class="p">,</span> mtry<span class="o">=</span>tune<span class="p">(),</span> learn_rate<span class="o">=</span>tune<span class="p">(),</span> 
                       tree_depth<span class="o">=</span>tune<span class="p">(),</span> min_n<span class="o">=</span>tune<span class="p">())</span> <span class="o">%&gt;%</span>
    set_engine<span class="p">(</span><span class="s">&#34;xgboost&#34;</span><span class="p">)</span> 

model_xgb</code></pre></div>
<pre><code>## Boosted Tree Model Specification (classification)
## 
## Main Arguments:
##   mtry = tune()
##   min_n = tune()
##   tree_depth = tune()
##   learn_rate = tune()
## 
## Computational engine: xgboost
</code></pre>

<hr />

<h4 id="6-4-1-hyperparameter-tunning">6.4.1 Hyperparameter tunning.</h4>

<p>This section took quite long to run the bayesian optimisation, so I
directly input the best parameters into the model, whenever I rerun the
model training section. The result below is a tuned model.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># # This section took very long to run, so</span>
<span class="c1"># # I directly input the best parameters into the model,</span>
<span class="c1"># # whenever I rerun the model training section.</span>
<span class="c1"># </span>
<span class="c1"># recipe_xgb = recipe(Satisfaction ~ ., data=df_train_processed)</span>
<span class="c1"># </span>
<span class="c1"># # Set the folds.</span>
<span class="c1"># set.seed(5)</span>
<span class="c1"># folds = vfold_cv(df_train_processed, v=10, strata=&#39;Satisfaction&#39;)</span>
<span class="c1"># </span>
<span class="c1"># # Set the metrics.</span>
<span class="c1"># class_metrics = yardstick::metric_set(accuracy, roc_auc, sensitivity, precision, f_meas, kap)</span>
<span class="c1"># </span>
<span class="c1"># # Set the workflow.</span>
<span class="c1"># xgb_wflow = workflow() %&gt;%</span>
<span class="c1">#     add_model(model_xgb) %&gt;%</span>
<span class="c1">#     add_recipe(recipe_xgb)</span>
<span class="c1">#     # add_formula(Satisfaction ~ .)</span>
<span class="c1"># </span>
<span class="c1"># # Set the range of parameters.</span>
<span class="c1"># xgb_param &lt;-</span>
<span class="c1">#     xgb_wflow %&gt;%</span>
<span class="c1">#     parameters() %&gt;%</span>
<span class="c1">#     update(</span>
<span class="c1">#         learn_rate = learn_rate(c(0.001, 0.5)),</span>
<span class="c1">#         tree_depth = tree_depth(c(3, 10)),</span>
<span class="c1">#         mtry = mtry(c(3, 9)),</span>
<span class="c1">#         min_n = min_n(c(50, 100))</span>
<span class="c1">#     )</span>
<span class="c1"># </span>
<span class="c1"># # Perform bayesian optimisation.</span>
<span class="c1"># set.seed(5)</span>
<span class="c1"># tuned_xgb = tune_bayes(xgb_wflow, resamples=folds, initial=5, iter=20, metrics=class_metrics,</span>
<span class="c1">#                        param_info=xgb_param, control=control_bayes(verbose=TRUE))</span></code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># # Show the results of various combination of parameters from Bayesian Optimisation.</span>
<span class="c1"># collect_metrics(tuned_xgb) %&gt;%</span>
<span class="c1">#     filter(.metric == &#39;sens&#39;) %&gt;%</span>
<span class="c1">#     arrange(desc(mean))</span></code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Fit the model with the best parameter. </span>
<span class="kp">set.seed</span><span class="p">(</span><span class="m">5</span><span class="p">)</span>
model_xgb <span class="o">=</span> boost_tree<span class="p">(</span>mode<span class="o">=</span><span class="s">&#34;classification&#34;</span><span class="p">,</span> mtry<span class="o">=</span><span class="m">9</span><span class="p">,</span> learn_rate<span class="o">=</span><span class="m">1.151495</span><span class="p">,</span> 
                       tree_depth<span class="o">=</span><span class="m">8</span><span class="p">,</span> min_n<span class="o">=</span><span class="m">54</span><span class="p">)</span> <span class="o">%&gt;%</span>
    set_engine<span class="p">(</span><span class="s">&#34;xgboost&#34;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    fit<span class="p">(</span>Satisfaction <span class="o">~</span> <span class="m">.</span><span class="p">,</span> data<span class="o">=</span>df_train_processed<span class="p">)</span></code></pre></div>
<hr />

<p>The table below shows the feature gain (aka feature importance).</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Show the feature gain. </span>
xgb.importance<span class="p">(</span>model<span class="o">=</span>model_xgb<span class="o">$</span>fit<span class="p">)</span> <span class="o">%&gt;%</span> 
    select<span class="p">(</span>Feature<span class="p">,</span> Gain<span class="p">)</span> <span class="o">%&gt;%</span> 
    arrange<span class="p">(</span>desc<span class="p">(</span>Gain<span class="p">))</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       Feature                             Gain          
##  [1,] &quot;Inflight_entertainment&quot;            &quot;0.4517750369&quot;
##  [2,] &quot;Seat_comfort&quot;                      &quot;0.1380882613&quot;
##  [3,] &quot;Onboard_service&quot;                   &quot;0.0581396517&quot;
##  [4,] &quot;Online_boarding&quot;                   &quot;0.0459806210&quot;
##  [5,] &quot;Baggage_handling&quot;                  &quot;0.0419795540&quot;
##  [6,] &quot;Class&quot;                             &quot;0.0406289410&quot;
##  [7,] &quot;CustomerType_loyal_customer&quot;       &quot;0.0398748884&quot;
##  [8,] &quot;Gate_location&quot;                     &quot;0.0345477063&quot;
##  [9,] &quot;Departure_Arrival_time_convenient&quot; &quot;0.0322028261&quot;
## [10,] &quot;Online_support&quot;                    &quot;0.0228241916&quot;
## [11,] &quot;Ease_of_Onlinebooking&quot;             &quot;0.0189583503&quot;
## [12,] &quot;TypeTravel_personal_travel&quot;        &quot;0.0137603249&quot;
## [13,] &quot;Checkin_service&quot;                   &quot;0.0110124126&quot;
## [14,] &quot;Cleanliness&quot;                       &quot;0.0109138182&quot;
## [15,] &quot;Leg_room_service&quot;                  &quot;0.0083444773&quot;
## [16,] &quot;Age_X_20_25_&quot;                      &quot;0.0081097684&quot;
## [17,] &quot;Food_drink&quot;                        &quot;0.0080467311&quot;
## [18,] &quot;Inflightwifi_service&quot;              &quot;0.0068892976&quot;
## [19,] &quot;DepartureDelayin_Mins&quot;             &quot;0.0039087491&quot;
## [20,] &quot;Age_X_25_30_&quot;                      &quot;0.0009463012&quot;
## [21,] &quot;Age_X_65_above_&quot;                   &quot;0.0007167897&quot;
## [22,] &quot;Age_X_50_55_&quot;                      &quot;0.0005906867&quot;
## [23,] &quot;Age_X_35_40_&quot;                      &quot;0.0005667831&quot;
## [24,] &quot;Age_X_30_35_&quot;                      &quot;0.0003317786&quot;
## [25,] &quot;Age_X_40_45_&quot;                      &quot;0.0002602920&quot;
## [26,] &quot;Age_X_45_50_&quot;                      &quot;0.0002197457&quot;
## [27,] &quot;Age_X_60_65_&quot;                      &quot;0.0002139177&quot;
## [28,] &quot;Age_X_55_60_&quot;                      &quot;0.0001680975&quot;
</code></pre>

<hr />

<h4 id="6-4-2-evaluate-the-model-performance">6.4.2 Evaluate the model performance.</h4>

<p>Compare the train and test result to see if it’s overfitting.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">model_train_performance <span class="o">=</span> df_train_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_xgb<span class="p">,</span> <span class="s">&#39;Model XGB&#39;</span><span class="p">,</span> 
                         model_train_performance<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;ensemble&#39;</span><span class="p">,</span> bind<span class="o">=</span><span class="kc">TRUE</span><span class="p">)</span>

model_train_performance</code></pre></div>
<pre><code>## # A tibble: 4 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model XGB              0.934  0.926 0.867     0.921   0.983 0.931
## 2 Model Random Forest    0.999  0.999 0.998     0.998   1.00  0.999
## 3 Model Decision Tree    0.918  0.907 0.834     0.911   0.965 0.903
## 4 Model GLM Logistic     0.833  0.811 0.661     0.814   0.907 0.809
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">model_test_performance <span class="o">=</span> df_test_processed <span class="o">%&gt;%</span> 
    evaluate_performance<span class="p">(</span>model_xgb<span class="p">,</span> <span class="s">&#39;Model XGB&#39;</span><span class="p">,</span> 
                         model_test_performance<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;ensemble&#39;</span><span class="p">,</span> bind<span class="o">=</span><span class="kc">TRUE</span><span class="p">)</span>

model_test_performance</code></pre></div>
<pre><code>## # A tibble: 4 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model XGB              0.930  0.920 0.858     0.913   0.982 0.928
## 2 Model Random Forest    0.952  0.946 0.903     0.937   0.992 0.955
## 3 Model Decision Tree    0.915  0.903 0.828     0.905   0.966 0.900
## 4 Model GLM Logistic     0.832  0.809 0.660     0.804   0.906 0.815
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># View the confusion matrix.</span>
df_test_processed <span class="o">%&gt;%</span> 
    make_prediction<span class="p">(</span>model_xgb<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;ensemble&#39;</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    conf_matrix_result<span class="p">()</span></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction     0     1
##          0 10089   960
##          1   783 13080
##                                           
##                Accuracy : 0.93            
##                  95% CI : (0.9268, 0.9332)
##     No Information Rate : 0.5636          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.858           
##                                           
##  Mcnemar's Test P-Value : 2.491e-05       
##                                           
##             Sensitivity : 0.9316          
##             Specificity : 0.9280          
##          Pos Pred Value : 0.9435          
##          Neg Pred Value : 0.9131          
##              Prevalence : 0.5636          
##          Detection Rate : 0.5250          
##    Detection Prevalence : 0.5565          
##       Balanced Accuracy : 0.9298          
##                                           
##        'Positive' Class : 1               
## 
</code></pre>

<hr />

<h2 id="7-save-the-models">7 Save the models.</h2>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># version = 3</span>
<span class="c1"># </span>
<span class="c1"># models_tbl = list(</span>
<span class="c1">#     &#34;MODEL_LOG_GLM&#34; = model_log_glm,</span>
<span class="c1">#     &#34;MODEL_LOG_GLM_ADJUSTED&#34; = model_log_glm_adjusted,</span>
<span class="c1">#     &#34;MODEL_DECISION_TREE&#34; = model_tree_decision,</span>
<span class="c1">#     &#34;MODEL_DECISION_TREE_PRUNED&#34; = model_tree_decision_pruned,</span>
<span class="c1">#     &#34;MODEL_RANDOM_FOREST&#34; = model_random_forest,</span>
<span class="c1">#     &#34;MODEL_XGBOOST&#34; = model_xgb) %&gt;%</span>
<span class="c1">#     enframe(name=&#34;model_id&#34;, value=&#34;model&#34;)</span>
<span class="c1"># </span>
<span class="c1"># models_tbl %&gt;% write_rds(str_glue(&#34;00_models/models_tbl_v{version}.rds&#34;))</span></code></pre></div>
<hr />

<h2 id="8-model-comparison">8 Model comparison.</h2>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Train.</span>
model_train_performance</code></pre></div>
<pre><code>## # A tibble: 4 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model XGB              0.934  0.926 0.867     0.921   0.983 0.931
## 2 Model Random Forest    0.999  0.999 0.998     0.998   1.00  0.999
## 3 Model Decision Tree    0.918  0.907 0.834     0.911   0.965 0.903
## 4 Model GLM Logistic     0.833  0.811 0.661     0.814   0.907 0.809
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Test.</span>
model_test_performance</code></pre></div>
<pre><code>## # A tibble: 4 x 7
##   model               accuracy f_meas   kap precision roc_auc  sens
##   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 Model XGB              0.930  0.920 0.858     0.913   0.982 0.928
## 2 Model Random Forest    0.952  0.946 0.903     0.937   0.992 0.955
## 3 Model Decision Tree    0.915  0.903 0.828     0.905   0.966 0.900
## 4 Model GLM Logistic     0.832  0.809 0.660     0.804   0.906 0.815
</code></pre>

<hr />

<h2 id="9-model-interpretation">9 Model interpretation.</h2>

<p>The table below shows the feature importance from the <code>Decision Tree</code>
after executing the complexity pruning.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r">model_tree_decision_pruned<span class="o">$</span>variable.importance <span class="o">%&gt;%</span> 
    <span class="kp">as.list</span><span class="p">()</span> <span class="o">%&gt;%</span> 
    as_tibble<span class="p">()</span> <span class="o">%&gt;%</span> 
    gather<span class="p">()</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>value <span class="o">=</span> <span class="kp">round</span><span class="p">(</span>value<span class="p">,</span> <span class="m">2</span><span class="p">))</span> <span class="o">%&gt;%</span> 
    set_names<span class="p">(</span><span class="kt">c</span><span class="p">(</span><span class="s">&#39;Feature&#39;</span><span class="p">,</span> <span class="s">&#39;Importance&#39;</span><span class="p">))</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       Feature                             Importance
##  [1,] &quot;Inflight_entertainment&quot;            &quot;11735.61&quot;
##  [2,] &quot;Seat_comfort&quot;                      &quot; 7535.76&quot;
##  [3,] &quot;Online_support&quot;                    &quot; 5539.10&quot;
##  [4,] &quot;Ease_of_Onlinebooking&quot;             &quot; 4853.10&quot;
##  [5,] &quot;Online_boarding&quot;                   &quot; 4023.79&quot;
##  [6,] &quot;Checkin_service&quot;                   &quot; 2251.94&quot;
##  [7,] &quot;Food_drink&quot;                        &quot; 1880.90&quot;
##  [8,] &quot;CustomerType_loyal_customer&quot;       &quot; 1140.57&quot;
##  [9,] &quot;Gate_location&quot;                     &quot;  898.83&quot;
## [10,] &quot;Departure_Arrival_time_convenient&quot; &quot;  829.23&quot;
## [11,] &quot;Cleanliness&quot;                       &quot;  819.90&quot;
## [12,] &quot;Onboard_service&quot;                   &quot;  804.52&quot;
## [13,] &quot;Inflightwifi_service&quot;              &quot;  646.38&quot;
## [14,] &quot;Baggage_handling&quot;                  &quot;  631.53&quot;
## [15,] &quot;Class&quot;                             &quot;  631.46&quot;
## [16,] &quot;Leg_room_service&quot;                  &quot;  613.96&quot;
## [17,] &quot;TypeTravel_personal_travel&quot;        &quot;  410.03&quot;
## [18,] &quot;Age_X_20_25_&quot;                      &quot;   15.91&quot;
## [19,] &quot;Age_X_65_above_&quot;                   &quot;   10.32&quot;
## [20,] &quot;DepartureDelayin_Mins&quot;             &quot;    6.97&quot;
## [21,] &quot;Age_X_60_65_&quot;                      &quot;    5.75&quot;
## [22,] &quot;Age_X_35_40_&quot;                      &quot;    4.45&quot;
## [23,] &quot;Age_X_25_30_&quot;                      &quot;    3.79&quot;
## [24,] &quot;Age_X_45_50_&quot;                      &quot;    1.71&quot;
## [25,] &quot;Age_X_30_35_&quot;                      &quot;    1.22&quot;
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># pdf(file=&#34;00_image/decision_tree_v1.pdf&#34;)</span>
<span class="c1"># rpart.plot(model_tree_decision_pruned, roundint=FALSE, type=2, extra=&#39;auto&#39;)</span>
<span class="c1"># dev.off()</span></code></pre></div>
<p><strong>Findings from the model performance table:</strong></p>

<ol>
<li>The <code>Random Forest</code> model scores the highest in all metrics.
However, it has high variance due to overfitting.</li>
<li>The <code>XGBoost</code> model is the second highest, with lower variance than
<code>Random Forest</code>.</li>
<li>The <code>Decision Tree</code> model is the third highest.</li>
</ol>

<p>Since <code>Decision Tree</code> has greater model interpretability and high
overall metric scores, I will go with this model instead. Nonetheless,
for model interpretation, I will pair this with the <code>Logistic</code> model
since the <code>Logistic</code> model is able shows us the increase or decrease in
odds ratio for each unit of X variable.</p>

<hr />

<p>The table below shows the feature weights from the <code>Logistic</code> model
after checking the VIF and adjusting the parameters with <code>StepAIC</code> by
removing or adding the parameters to get the lowest AIC.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Finalised model. </span>
<span class="c1"># Preview the variable weights. </span>
broom<span class="o">::</span>tidy<span class="p">(</span>model_log_glm_adjusted<span class="p">)</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>estimate_abs <span class="o">=</span> <span class="kp">abs</span><span class="p">(</span>estimate<span class="p">))</span> <span class="o">%&gt;%</span> 
    arrange<span class="p">(</span>desc<span class="p">(</span>estimate_abs<span class="p">))</span> <span class="o">%&gt;%</span> 
    select<span class="p">(</span>term<span class="p">,</span> estimate<span class="p">)</span> <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>estimate <span class="o">=</span> <span class="kp">round</span><span class="p">(</span>estimate<span class="p">,</span> <span class="m">4</span><span class="p">))</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       term                                estimate  
##  [1,] &quot;(Intercept)&quot;                       &quot;-11.5219&quot;
##  [2,] &quot;CustomerType_loyal_customer&quot;       &quot;  2.0452&quot;
##  [3,] &quot;TypeTravel_personal_travel&quot;        &quot; -0.7768&quot;
##  [4,] &quot;Inflight_entertainment&quot;            &quot;  0.7158&quot;
##  [5,] &quot;Age_X_20_25_&quot;                      &quot;  0.6252&quot;
##  [6,] &quot;Class&quot;                             &quot;  0.3470&quot;
##  [7,] &quot;Age_X_65_above_&quot;                   &quot; -0.3296&quot;
##  [8,] &quot;Onboard_service&quot;                   &quot;  0.3095&quot;
##  [9,] &quot;Checkin_service&quot;                   &quot;  0.2986&quot;
## [10,] &quot;Seat_comfort&quot;                      &quot;  0.2916&quot;
## [11,] &quot;Leg_room_service&quot;                  &quot;  0.2462&quot;
## [12,] &quot;Ease_of_Onlinebooking&quot;             &quot;  0.2250&quot;
## [13,] &quot;Departure_Arrival_time_convenient&quot; &quot; -0.2233&quot;
## [14,] &quot;Food_drink&quot;                        &quot; -0.1926&quot;
## [15,] &quot;DepartureDelayin_Mins&quot;             &quot; -0.1810&quot;
## [16,] &quot;Online_boarding&quot;                   &quot;  0.1587&quot;
## [17,] &quot;Gate_location&quot;                     &quot;  0.1285&quot;
## [18,] &quot;Online_support&quot;                    &quot;  0.1010&quot;
## [19,] &quot;Baggage_handling&quot;                  &quot;  0.0934&quot;
## [20,] &quot;Cleanliness&quot;                       &quot;  0.0917&quot;
## [21,] &quot;Inflightwifi_service&quot;              &quot; -0.0651&quot;
</code></pre>

<p><strong>Findings on the feature importance from <code>Decision Tree</code>:</strong></p>

<ol>
<li>The top 5 important features are <code>inflight_entertainment</code>,
<code>Seat_comfort</code>, <code>Ease_of_Onlinebooking</code>, <code>Online_boarding</code>,
<code>Online_support</code>. These should mostly likely be the baseline for
customer satisfaction.</li>
<li>Customers at different age group do not seem to have any significant
impact on customer satisfaction although customers aged between
20-25 seem to have greater impact than the rest of the age groups
(perhaps due to different opinion or perspective).</li>
<li><code>DepartureDelayin_Mins</code> also do not seem to have any significant
impact on customer satisfaction, regardless of the time length. It’s
rather the <code>Depature_Arrival_time_convenient</code> feature that is
affecting the customer satisfaction. We can find out more from the
logistic model on this.</li>
</ol>

<p>I can explore with the top N important features incrementally to
investigate the business impact of the improved features (increased
rating) on the proportion of customers feeling satisfied and reduction
in customer churn cost. However, there is a limitation on the model
interpretation. For example, in real world, even if the model is 100%
perfect and we were able to increase the rating for
<code>Inflight_entertainment</code> to 5 (good) or above (excellent), some
customers’ satisfaction might still not be affected since different
customers prioritise or view the features differently. We only assume
most customers would be affected by that feature.</p>

<p>To reduce the business risk, we can extend this research further by
conducting several interviews with various segment of customers to find
out more.</p>

<hr />

<h2 id="10-explore-the-important-variable-s-effect-on-the-cost-of-customer-churn">10 Explore the important variable’s effect on the cost of customer churn.</h2>

<h3 id="10-1-find-the-optimal-discriminant-threshold">10.1 Find the optimal discriminant threshold.</h3>

<p>After some exploration, to avoid underestimating the customer churn cost
for loyal business and personal travellers who are neutral/dissatisfied,
the discriminant threshold should at least be around 0.75.</p>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># To avoid underestimating the customer churn cost</span>
<span class="c1"># for loyal business and personal travellers, </span>
<span class="c1"># the threshold should at least be this. </span>
prob_threshold <span class="o">=</span> <span class="m">.75</span>

<span class="c1"># Predict the probability of customer feeling satisfied </span>
<span class="c1"># and compute the the life time value.</span>
predicted_customer_churn_cost <span class="o">=</span> df_train_processed <span class="o">%&gt;%</span> 
    make_prediction<span class="p">(</span>model_tree_decision_pruned<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;prob&#39;</span><span class="p">,</span> threshold<span class="o">=</span>prob_threshold<span class="p">)</span> <span class="o">%&gt;%</span> 
    bind_cols<span class="p">(</span>df_train_processed_with_id <span class="o">%&gt;%</span> select<span class="p">(</span><span class="o">-</span>Satisfaction<span class="p">))</span> <span class="o">%&gt;%</span> 
    select<span class="p">(</span>CustomerId<span class="p">,</span> <span class="m">.</span>pred_satisfied<span class="p">,</span> <span class="m">.</span>pred_class<span class="p">,</span> Satisfaction<span class="p">,</span> everything<span class="p">())</span> <span class="o">%&gt;%</span> 
    compute_customer_life_time_value<span class="p">(</span>travel_type_colname<span class="o">=</span>TypeTravel_personal_travel<span class="p">)</span></code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Estimate the cost of customer churn for loyal customers. </span>
predicted_customer_churn_cost <span class="o">%&gt;%</span>
    life_time_value_by_customer_type<span class="p">(</span><span class="m">.</span>pred_class<span class="p">,</span> CustomerType_loyal_customer<span class="p">,</span> TypeTravel_personal_travel<span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   .pred_class CustomerType_loyal_cu… TypeTravel_personal… total_customer_life_t…
##   &lt;fct&gt;                        &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;                 
## 1 0                                0                    0 $23,351,850           
## 2 0                                0                    1 $44,300               
## 3 0                                1                    0 $26,604,450           
## 4 0                                1                    1 $6,496,500            
## 5 1                                0                    0 $4,350,750            
## 6 1                                0                    1 $5,200                
## 7 1                                1                    0 $72,694,950           
## 8 1                                1                    1 $4,592,700
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Actual cost of customer churn for loyal customers. </span>
predicted_customer_churn_cost <span class="o">%&gt;%</span>
    life_time_value_by_customer_type<span class="p">(</span>Satisfaction<span class="p">,</span> CustomerType_loyal_customer<span class="p">,</span> TypeTravel_personal_travel<span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   Satisfaction CustomerType_loyal_c… TypeTravel_personal… total_customer_life_t…
##   &lt;fct&gt;                        &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;                 
## 1 0                                0                    0 $20,283,150           
## 2 0                                0                    1 $43,000               
## 3 0                                1                    0 $26,217,300           
## 4 0                                1                    1 $5,949,150            
## 5 1                                0                    0 $7,419,450            
## 6 1                                0                    1 $6,500                
## 7 1                                1                    0 $73,082,100           
## 8 1                                1                    1 $5,140,050
</code></pre>

<hr />

<h3 id="10-2-compare-the-new-estimated-customer-churn-cost-after-improving-the-rating">10.2 Compare the new estimated customer churn cost after improving the rating.</h3>

<h4 id="10-2-1-explore-on-train-set">10.2.1 Explore on TRAIN set.</h4>

<p>I will first explore the following top 5 important features to see the
effect by increasing the rating to 5 (good) or above (excellent). Then I
will estimate the customer life time value after increasing the rating
for these 5 features and making model prediction:</p>

<ol>
<li>Inflight entertainment.</li>
<li>Seat comfort.</li>
<li>Online support.</li>
<li>Ease of online booking.</li>
<li>Online boarding.</li>
</ol>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Predict the probability of customer feeling satisfied </span>
<span class="c1"># and compute the the life time value </span>
<span class="c1"># after reassigning / improving the ratings for the top 5 variables/features. </span>
predicted_customer_churn_cost_on_train <span class="o">=</span> df_train_processed <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>
        Inflight_entertainment <span class="o">=</span> Inflight_entertainment <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Seat_comfort <span class="o">=</span> Seat_comfort <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Online_support <span class="o">=</span> Online_support <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Ease_of_Onlinebooking <span class="o">=</span> Ease_of_Onlinebooking <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Online_boarding <span class="o">=</span> Online_boarding <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">)</span>
    <span class="p">)</span> <span class="o">%&gt;%</span>

    make_prediction<span class="p">(</span>model_tree_decision_pruned<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;prob&#39;</span><span class="p">,</span> threshold<span class="o">=</span>prob_threshold<span class="p">)</span> <span class="o">%&gt;%</span> 
    bind_cols<span class="p">(</span>df_train_processed_with_id <span class="o">%&gt;%</span> select<span class="p">(</span><span class="o">-</span>Satisfaction<span class="p">))</span> <span class="o">%&gt;%</span> 
    select<span class="p">(</span>CustomerId<span class="p">,</span> <span class="m">.</span>pred_satisfied<span class="p">,</span> <span class="m">.</span>pred_class<span class="p">,</span> Satisfaction<span class="p">,</span> everything<span class="p">())</span> <span class="o">%&gt;%</span> 
    compute_customer_life_time_value<span class="p">(</span>travel_type_colname<span class="o">=</span>TypeTravel_personal_travel<span class="p">)</span> </code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Estimate the cost of customer churn for loyal customers. </span>
predicted_customer_churn_cost_on_train <span class="o">%&gt;%</span>
    life_time_value_by_customer_type<span class="p">(</span><span class="m">.</span>pred_class<span class="p">,</span> CustomerType_loyal_customer<span class="p">,</span> TypeTravel_personal_travel<span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   .pred_class CustomerType_loyal_cu… TypeTravel_personal… total_customer_life_t…
##   &lt;fct&gt;                        &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;                 
## 1 0                                0                    0 $24,811,950           
## 2 0                                0                    1 $46,900               
## 3 0                                1                    0 $9,199,200            
## 4 0                                1                    1 $2,970,100            
## 5 1                                0                    0 $2,890,650            
## 6 1                                0                    1 $2,600                
## 7 1                                1                    0 $90,100,200           
## 8 1                                1                    1 $8,119,100
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Actual cost of customer churn for loyal customers. </span>
predicted_customer_churn_cost_on_train <span class="o">%&gt;%</span>
    life_time_value_by_customer_type<span class="p">(</span>Satisfaction<span class="p">,</span> CustomerType_loyal_customer<span class="p">,</span> TypeTravel_personal_travel<span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   Satisfaction CustomerType_loyal_c… TypeTravel_personal… total_customer_life_t…
##   &lt;fct&gt;                        &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;                 
## 1 0                                0                    0 $20,283,150           
## 2 0                                0                    1 $43,000               
## 3 0                                1                    0 $26,217,300           
## 4 0                                1                    1 $5,949,150            
## 5 1                                0                    0 $7,419,450            
## 6 1                                0                    1 $6,500                
## 7 1                                1                    0 $73,082,100           
## 8 1                                1                    1 $5,140,050
</code></pre>

<hr />

<h4 id="10-2-2-explore-on-test-set">10.2.2 Explore on TEST set.</h4>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Predict the probability of customer feeling satisfied </span>
<span class="c1"># and compute the the life time value </span>
<span class="c1"># after reassigning / improving the ratings for the top 5 variables/features. </span>
predicted_customer_churn_cost_on_test <span class="o">=</span> df_test_processed <span class="o">%&gt;%</span> 
    mutate<span class="p">(</span>
        Inflight_entertainment <span class="o">=</span> Inflight_entertainment <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Seat_comfort <span class="o">=</span> Seat_comfort <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Online_support <span class="o">=</span> Online_support <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Ease_of_Onlinebooking <span class="o">=</span> Ease_of_Onlinebooking <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">),</span>
        Online_boarding <span class="o">=</span> Online_boarding <span class="o">%&gt;%</span> reassign_rating<span class="p">(</span><span class="m">5</span><span class="p">)</span>
    <span class="p">)</span> <span class="o">%&gt;%</span>

    make_prediction<span class="p">(</span>model_tree_decision_pruned<span class="p">,</span> predict_type<span class="o">=</span><span class="s">&#39;prob&#39;</span><span class="p">,</span> threshold<span class="o">=</span>prob_threshold<span class="p">)</span> <span class="o">%&gt;%</span> 
    bind_cols<span class="p">(</span>df_test_processed_with_id <span class="o">%&gt;%</span> select<span class="p">(</span><span class="o">-</span>Satisfaction<span class="p">))</span> <span class="o">%&gt;%</span> 
    select<span class="p">(</span>CustomerId<span class="p">,</span> <span class="m">.</span>pred_satisfied<span class="p">,</span> <span class="m">.</span>pred_class<span class="p">,</span> Satisfaction<span class="p">,</span> everything<span class="p">())</span> <span class="o">%&gt;%</span> 
    compute_customer_life_time_value </code></pre></div><div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Estimate the cost of customer churn for loyal customers. </span>
predicted_customer_churn_cost_on_test <span class="o">%&gt;%</span>
    life_time_value_by_customer_type<span class="p">(</span><span class="m">.</span>pred_class<span class="p">,</span> CustomerType_loyal_customer<span class="p">,</span> TypeTravel_personal_travel<span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   .pred_class CustomerType_loyal_cu… TypeTravel_personal… total_customer_life_t…
##   &lt;fct&gt;                        &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;                 
## 1 0                                0                    0 $3,468,550            
## 2 0                                0                    1 $14,500               
## 3 0                                1                    0 $1,332,050            
## 4 0                                1                    1 $1,320,450            
## 5 1                                0                    0 $430,550              
## 6 1                                0                    1 $2,600                
## 7 1                                1                    0 $12,771,700           
## 8 1                                1                    1 $3,510,400
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Actual cost of customer churn for loyal customers. </span>
predicted_customer_churn_cost_on_test <span class="o">%&gt;%</span>
    life_time_value_by_customer_type<span class="p">(</span>Satisfaction<span class="p">,</span> CustomerType_loyal_customer<span class="p">,</span> TypeTravel_personal_travel<span class="p">)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   Satisfaction CustomerType_loyal_c… TypeTravel_personal… total_customer_life_t…
##   &lt;fct&gt;                        &lt;dbl&gt;                &lt;dbl&gt; &lt;chr&gt;                 
## 1 0                                0                    0 $2,810,450            
## 2 0                                0                    1 $12,550               
## 3 0                                1                    0 $3,643,400            
## 4 0                                1                    1 $2,550,400            
## 5 1                                0                    0 $1,088,650            
## 6 1                                0                    1 $4,550                
## 7 1                                1                    0 $10,460,350           
## 8 1                                1                    1 $2,280,450
</code></pre>

<hr />

<p><strong>Findings after increasing the rating, making prediction, and
calculating the value on TEST data (30% rows):</strong></p>

<ol>
<li>After calculating the difference between the before and after, the
company is able to save 3.54 million (6.19 – 2.65 million) roughly
on loyal Business and Personal Travellers who are
neutral/dissatisfied, which is around 57% of reduction just by
focusing on improving the top 5 important features.</li>
</ol>

<hr />

<h3 id="10-3-compare-the-proportion-of-the-neutral-unsatisfied-customers-after-improving-the-rating">10.3 Compare the proportion of the neutral/unsatisfied customers after improving the rating.</h3>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Actual proportion of neutral/unsatisfied customer. </span>
df_falconAirlines<span class="o">$</span>Satisfaction <span class="o">%&gt;%</span> <span class="kp">summary</span><span class="p">()</span> <span class="o">/</span> <span class="kp">nrow</span><span class="p">(</span>df_falconAirlines<span class="p">)</span></code></pre></div>
<pre><code>## neutral_or dissatisfied               satisfied 
##               0.4526766               0.5473234
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># On TRAIN. </span>
<span class="c1"># Estimated proportion of neutral/unsatisfied customer after improving the rating. </span>
predicted_customer_churn_cost_on_train<span class="o">$</span><span class="m">.</span>pred_class <span class="o">%&gt;%</span> <span class="kp">summary</span><span class="p">()</span> <span class="o">/</span> <span class="kp">nrow</span><span class="p">(</span>predicted_customer_churn_cost_on_train<span class="p">)</span></code></pre></div>
<pre><code>##         0         1 
## 0.2910691 0.7089309
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># On TEST.  </span>
<span class="c1"># Estimated proportion of neutral/unsatisfied customer after improving the rating. </span>
predicted_customer_churn_cost_on_test<span class="o">$</span><span class="m">.</span>pred_class <span class="o">%&gt;%</span> <span class="kp">summary</span><span class="p">()</span> <span class="o">/</span> <span class="kp">nrow</span><span class="p">(</span>predicted_customer_churn_cost_on_test<span class="p">)</span></code></pre></div>
<pre><code>##        0        1 
## 0.291466 0.708534
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Check the range of reduction in neutral/dissatisfied customer</span>
<span class="c1"># based on different threshold. </span>
predicted_customer_churn_cost_on_test <span class="o">%&gt;%</span> 
    predicted_prob_percentile<span class="p">()</span> <span class="o">%&gt;%</span> 
    filter<span class="p">(</span>prob <span class="o">&lt;=</span> <span class="m">0.8</span><span class="p">)</span> <span class="o">%&gt;%</span> 
    <span class="kp">as.matrix</span><span class="p">()</span></code></pre></div>
<pre><code>##       percentile prob    
##  [1,] &quot;0%&quot;       &quot;0.0000&quot;
##  [2,] &quot;2.5%&quot;     &quot;0.0000&quot;
##  [3,] &quot;5%&quot;       &quot;0.2941&quot;
##  [4,] &quot;7.5%&quot;     &quot;0.3012&quot;
##  [5,] &quot;10%&quot;      &quot;0.3012&quot;
##  [6,] &quot;12.5%&quot;    &quot;0.3012&quot;
##  [7,] &quot;15%&quot;      &quot;0.3012&quot;
##  [8,] &quot;17.5%&quot;    &quot;0.3237&quot;
##  [9,] &quot;20%&quot;      &quot;0.3237&quot;
## [10,] &quot;22.5%&quot;    &quot;0.6031&quot;
## [11,] &quot;25%&quot;      &quot;0.6031&quot;
## [12,] &quot;27.5%&quot;    &quot;0.6031&quot;
## [13,] &quot;30%&quot;      &quot;0.7554&quot;
</code></pre>

<hr />

<p><strong>Findings on the predicted probability by Decision Tree after
increasing the rating:</strong></p>

<ol>
<li>The proportion of the predicted neutral/dissatisfied customers is
reduced from 45% to between 22.5–30% (between 0.5 to 0.75
discriminant threshold), which is 15–22.5% of difference just by
focusing on improving the top 5 important features.</li>
</ol>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Proportion of customers type who are satisfied or neutral/dissatisfied. </span>
predicted_customer_churn_cost_on_test <span class="o">%&gt;%</span> 
    select<span class="p">(</span>CustomerType_loyal_customer<span class="p">,</span> Satisfaction<span class="p">)</span> <span class="o">%&gt;%</span> 
    group_by<span class="p">(</span>CustomerType_loyal_customer<span class="p">,</span> Satisfaction<span class="p">)</span> <span class="o">%&gt;%</span> 
    summarise<span class="p">(</span>Counts<span class="o">=</span>n<span class="p">())</span> <span class="o">%&gt;%</span> 
    ungroup<span class="p">()</span> </code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   CustomerType_loyal_customer Satisfaction Counts
##                         &lt;dbl&gt; &lt;fct&gt;         &lt;int&gt;
## 1                           0 0              3426
## 2                           0 1              1110
## 3                           1 0              7446
## 4                           1 1             12930
</code></pre>
<div class="highlight"><pre class="chroma"><code class="language-r" data-lang="r"><span class="c1"># Proportion of customers type who are satisfied or neutral/dissatisfied. </span>
predicted_customer_churn_cost_on_test <span class="o">%&gt;%</span> 
    select<span class="p">(</span>CustomerType_loyal_customer<span class="p">,</span> <span class="m">.</span>pred_class<span class="p">)</span> <span class="o">%&gt;%</span> 
    group_by<span class="p">(</span>CustomerType_loyal_customer<span class="p">,</span> <span class="m">.</span>pred_class<span class="p">)</span> <span class="o">%&gt;%</span> 
    summarise<span class="p">(</span>Counts<span class="o">=</span>n<span class="p">())</span> <span class="o">%&gt;%</span> 
    ungroup<span class="p">()</span> </code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   CustomerType_loyal_customer .pred_class Counts
##                         &lt;dbl&gt; &lt;fct&gt;        &lt;int&gt;
## 1                           0 0             4101
## 2                           0 1              435
## 3                           1 0             3160
## 4                           1 1            17216
</code></pre>

<p><strong>Findings:</strong></p>

<ol>
<li>The table shows around 57.6% of reduction ((7446 – 3160) / 7446) for
neutral/dissatisfied loyal customers just by focusing on improving
the top 5 important features.</li>
</ol>

<hr />

<h2 id="11-conclusion">11 Conclusion.</h2>

<p><strong>The following recommendations focus on loyal customers who are
neutral/dissatisfied:</strong></p>

<ol>
<li>Extend the user research to interviews with different segment of
customers after performing the customer segmentation, especially
with personal travellers to find out more on customer preference. We
can also inquire them about the top N important features to
understand why they matters to them. We can also find out what makes
a customer loyal to our FalconAirlines brand so that we can also
target the disloyal customers who are neutral/dissatisfied.</li>
<li>Extend the user research to value mapping to map out and analyse the
customer touchpoint and user journey.</li>
<li>Investigate the <code>Departure_Arrival_time_convenient</code> and <code>Food_drink</code>
data as there could be a data error (refer to section 3.3 on
negative performing feature — bullet 2).</li>
<li>Analyse the current business capabilities for the top N important
features before moving to the business transformation planning. We
can then estimate the potential reduction in customer churn cost for
features that the business is capable to plan and execute for that
time period.</li>
<li>We might want to pay extra attention to loyal business travellers
since the customer churn cost is higher as they travel more
frequently than the personal travellers. Plus, about 69% of our
customers are business travellers based on the current data.</li>
</ol>

    </div>
  </div>
  
</article>


        
                </div>
            </div>
        </div>


        
        </br>
        <footer class="footer text-center">
            <div class="container">
                <span class="text-muted">
                    Copyright &copy; Lionel Tay Yee Dang, <time datetime="2021">2021</time>.
                </span>
            </div>
        </footer>


        
        <a id="custom_github" class="btn btn-primary btn-lg" href="https://github.com/lioneltayyd" role="button" title="To Github" data-toggle="tooltip" data-placement="bottom">
            <i class="fab fa-github-alt"></i>
        </a> 
        <a id="custom_linkedin" class="btn btn-primary btn-lg" href="https://www.linkedin.com/in/lioneltayyd/" role="button" title="To Linkedin" data-toggle="tooltip" data-placement="bottom">
            <i class="fab fa-linkedin-in"></i>
        </a> 
        <a id="custom_back_to_top" class="btn btn-primary btn-lg" href="#" role="button" title="Back to the top" data-toggle="tooltip" data-placement="bottom">
            <i class="fas fa-arrow-up"></i>
        </a>


        
        <script 
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
            crossorigin="anonymous"></script>
        <script 
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
            crossorigin="anonymous"></script>
        <script 
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
            crossorigin="anonymous"></script>

    </body>

</html>
